import re

def process_file():
    with open("chapters/05_tartisma_ve_sonuc.qmd", "r", encoding="utf-8") as f:
        content = f.read()

    replacements = {
        'Pinquart\'ın 325 farklı çalışmayı birleştirdiği devasa incelemesine (meta-analiz) bakılabilir.': 'Pinquart\'ın 325 farklı çalışmayı sentezlediği kapsamlı meta-analizi incelenebilir.',
        'en çok göze çarpan değişiklik': 'en belirgin değişim',
        'çok iyi uyuşmaktadır.': 'tutarlılık göstermektedir.',
        'neredeyse aynı boyuttadır.': 'benzer düzeydedir.',
        'son derece ciddiye alınması gereken': 'klinik olarak dikkate alınması gereken',
        'Zaten annelerin "kendi ebeveynliklerini puanladığı" anketler (öz-rapor) doğası gereği yanıltıcı olmaya çok müsaittir.': 'Öz-bildirime (self-report) dayalı ölçümlerin yapısal doğası da bu ayrışmaya zemin hazırlamaktadır.',
        'Daha da önemlisi, annenin hissettiği depresyon sadece kendi psikolojisinde kalmamakta, çocuğun algısına doğrudan sıçramaktadır.': 'Maternal depresif belirtiler yalnız annenin içsel deneyimi olarak kalmamakta, çocuğun algısal dünyasına doğrudan geçişkenlik (spillover) göstermektedir.',
        'İşin ilginç yanı, annelerin anketlerde (kendi beyanlarında) bu etkiyi gereğinden fazla şişirme eğiliminde olmasıdır': 'Annelerin öz-bildirim araçlarında bu etkiyi gözlemsel gerçekliğin ötesinde raporlama eğilimi ise literatürde yöntem varyansı olarak açıklanmaktadır',
        'Kısacası, anne \'ben sıcak bir anneyim\' dese de önemli olan çocuğun bunu nasıl hissettiğidir.': 'Bu bulgular, koruyucu ebeveynliğin yalnızca anne beyanıyla değil çocuğun algısı üzerinden değerlendirilmesinin elzem olduğunu vurgular.',
        'İlk başta sınırda bir fark görülse de': 'Sıcaklık boyutunda başlangıçta sınırda bir farklılık izlense de',
        'Asıl fark, **sorunun kime (anneye mi yoksa çocuğa mı) sorulduğuna göre değişen ayrışmadır**.': 'Temel ayrışma, **aynı ebeveynlik tutumunun farklı bilgi-vericiler (anne ve çocuk) tarafından nasıl algılandığına** dayanmaktadır.',
        'dev çalışmada da': 'kapsamlı çalışmada da',
        'İşte bu uyumsuzluk, bu tezin sonuçlarını anlamak için çok kritik iki kurala işaret eder': 'Bu diadik uyumsuzluk, çalışmanın bulgularını yorumlamada iki temel ölçüm ilkesini öne çıkarır',
        'tam da bu eksikliği kapatmak içindir': 'doğrudan bu boşluğu doldurmayı amaçlar',
        'Bu nedenle annelerin "biz çocuğumuzu reddetmiyoruz" demesi (bizim çalışmamızdaki H3 hipoteziyle) tamamen aynıdır.': 'Nitekim ilgili çalışmadaki annelerin reddedici tutum bildirmemesi, mevcut çalışmanın H3 (anne öz-bildiriminde fark yokluğu) bulgusuyla paralellik gösterir.',
        'Çalışmamızın belki de en önemli bulgularından biri, anne ile çocuğun aynı evdeki \'ebeveynliği\' ne kadar farklı algıladıklarıdır': 'Bu araştırmanın temel çıkarımlarından biri de aynı haneyi paylaşan anne ve çocuğun ebeveynlik süreçlerini ne derece farklı deneyimlediğidir',
        'Beş farklı yöntemle yaptığımız inceleme, annenin kendi ebeveynliği ile çocuğun bunu nasıl hissettiği arasındaki uyumun son derece düşük olduğunu göstermiştir': 'Beş farklı istatistiksel strateji ile yürütülen çok-yöntemli analiz, anne öz-bildirimi ile çocuk algısı arasındaki diadik tutarlılığın düşük olduğunu doğrulamıştır',
        'Sayısal veriler bize uyumun ne kadar kopuk olduğunu gösterirken, tezin niteliksel tarafı bunun nedenlerini açıklar.': 'Sayısal veriler bu diadik kopukluğun şiddetini belgelerken, çalışmanın nitel boyutu bu ayrışmanın bağlamsal kökenlerini aydınlatmaktadır.',
        'Dahası, anneler her zaman kendilerini çocuklarının onları gördüğünden daha \'olumlu\' değerlendirme eğilimindedir.': 'Dahası ebeveynler, öz-bildirim ölçümlerinde kendi tutumlarını çocuklarının algısına kıyasla daha olumlu raporlama yönelimindedir.',
        'birinin yalan söylemesi veya ölçümün yanlış olması" olarak değil, "herkesin o durumu kendi penceresinden (durumsal özgüllük) haklı olarak farklı yaşaması" biçiminde açıklamıştır': 'bir ölçüm hatası veya yanlılık olarak değil, her bireyin ilişkiyi kendi bağlamından geçerli bir şekilde farklı deneyimlemesi (durumsal özgüllük) olarak kavramlaştırmıştır',
        'Kısacası, anne ve çocuğun farklı şeyler söylemesi anketin bir hatası değil, gerçekliğin kendisidir': 'Dolayısıyla bilgi-vericiler arası uyuşmazlık ölçümsel bir hata değil, ilişkisel dinamiklerin yapısal bir yansımasıdır',
        'başka sonuçlar çıkarmasını şöyle açıklar: Her biri çocuğu farklı bir bağlamda, farklı amaçlarla gözlemler.': 'farklı bildirimlerde bulunmasını bağlamsal değişkenlikle açıklar: Bilgi-vericiler hedef davranışları farklı ortamlarda ve farklı beklentilerle değerlendirir.',
        'Dolayısıyla ifadeler uyuşmadığında kimse \'yanılmaz\', aksine her biri kendi bulunduğu bağlamın doğrusunu söyler': 'Bu perspektiften, uyuşmazlık bir geçersizlik göstergesi değil, her bir gözlemcinin kendi bağlamına özgü geçerli bir bilgi taşıdığı anlamına gelir',
        'Bu gözle bakıldığında, araştırmamızda annelerin ve çocukların cevaplarının birleşmemesi bir ölçüm veya anket hatası değil, gayet beklenen, doğal bir bulgudur': 'Bu çerçevede, mevcut araştırmada izlenen anne-çocuk bildirim ayrışması da beklenen yapısal bir sonuç olarak değerlendirilmelidir',
        '"bize özel" dediğimiz sırdan oluşur.': 'karşılıklı, kendilerine özgü (diadik) ilişkisel tarihten beslenir.',
        'Tam da bu sebeple tezimizin en özgün tarafı şudur: "Neden anne ve çocuk uyuşmuyor?" sorusunun cevabını niteliksel derin görüşmelerimiz vermiştir.': 'Bu bağlamda karma tasarımın temel katkısı, "bilgi-verici uyuşmazlığının ardında yatan mekanizma nedir?" sorusuna nitel verilerle yanıt verebilmesidir.',
        'Diyabetli bir ailede anne "düzen, güvence ve tıbbi sorumluluk" diliyle konuşurken, diyabetli çocuk "bedenime müdahale etme, arkadaşlarım bana acımasın" diliyle, sağlıklı kardeş ise "hep ona odaklanıyorsunuz, bana haksızlık yapılıyor" diliyle konuşur.': 'Niteliksel temalar; annenin tıbbi sorumluluk ve güvenlik eksenli, indeks çocuğun bedensel özerklik ve sosyal algı temelli, sağlıklı kardeşin ise adaletsizlik ve ikincilleştirilme odaklı anlam dünyaları inşa ettiğini göstermiştir.',
        'Bu üç rol, aynı evde yaşasa da aslında üç farklı dünya yaşamaktadır.': 'Bu durum aynı hanedeki üç aktörün yapısal olarak farklı fenomenolojik konumlar deneyimlediğine işaret eder.',
        'Bizim tezimiz basitçe "ebeveynler diyabetli çocuğa nasıl davranır" demek yerine, "aynı eylemin bu üç kişi tarafından nasıl bambaşka anlaşıldığını" haritalandırmaktadır.': 'Çalışma ebeveynlik davranışının nesnel bir dökümünü sunmaktan ziyade, aynı davranışsal tutumun bu üç bilgi-verici tarafından nasıl farklı anlamlandırıldığını (fenomenolojik ayrışmayı) belgelemiştir.',
        'Rakamların bize gösterdiği bu \'uyumsuzluğun\', derinlemesine görüşmelerle ruhunu bulduğu yer burasıdır.': 'Nicel bulgularda saptanan istatistiksel uyumsuzluğun bağlamsal derinliği bu nitel temalarla bütünleşmektedir.',
        '- **Açıklayıcı genişleme**: Anketlerin (sayıların) bize gösterdiği durumun \'gerçek hayatta nasıl yaşandığını\' derinlemesine görüşmelerin anlatmasıdır.': '- **Açıklayıcı genişleme**: Nicel istatistiklerin saptadığı yapısal durumların (örneğin diadik uyumsuzluğun) nitel görüşmeler üzerinden bağlamsal olarak derinleştirilmesidir.',
        'Annelerin anketlerde kontrol grubuyla aynı puanları alması, ortada bir yük olmadığı anlamına gelmez. Görüşmeler göstermiştir ki anneler bu ağır bakım işini bir "annelik görevi" olarak o kadar içselleştirmiştir ki, bunu bir şikayet unsuru olarak anketlere yansıtmamaktadır.': 'Annelerin öz-bildirim ölçeklerinde kontrol grubuyla benzer düzeyde puan alması ebeveynlik yükünün yokluğundan ziyade, ağır diyabet yönetiminin ahlaki bir annelik sorumluluğu olarak içselleştirildiğini ve bu nedenle anket formatında şikayet olarak kodlanmadığını düşündürmektedir.',
        'Anketlerde anne ve çocuğun cevaplarının birbirini tutmamasının nedeni anketin hatalı olması değil; anne, diyabetli çocuk ve kardeşin hastalık sürecini bambaşka pencerelerden yaşamalarıdır.': 'Ölçümlerde izlenen uyuşmazlıklar salt hata varyansından (ölçüm yanlılığından) kaynaklanmamakta; aktörlerin (anne, indeks, kardeş) hastalığa yönelik öznel deneyim alanlarının yapısal farklılığını yansıtmaktadır.',
        'Tüm bu birleşimler bize şunu söyler: Çalışmamızın en büyük katkısı, "anne ve çocuk farklı şeyler söylüyor, demek ki veriler hatalı" demek yerine; "bu fark, olayın ta kendisidir" gerçeğini ortaya koymasıdır.': 'Karma bütünleştirme sonuçları, bilgi-vericiler arası farklılıkların geçersiz bir ölçümü değil, fenomenolojik olarak çoklu ve geçerli bir aile gerçekliğini temsil ettiğini doğrular.',
        'Elbette niteliksel çalışmadaki 7 aileyi, anket yaptığımız 241 aileye matematiksel olarak genellemiyoruz; sadece rakamların ardındaki ruhu anlamak için tamamlayıcı bir kanıt olarak sunuyoruz.': 'Niteliksel örneklem grubundan (n=7) elde edilen temalar evrene istatistiksel bir genelleme iddiası taşımaz; ancak nicel sonuçların arkasındaki nedensel mekanizmaları ve öznelliği anlamlandırmak için kavramsal bir derinlik sunar.',
        '"Annenin depresyonu ebeveynliğini bozar, bozulan ebeveynlik de çocuğa reddedilme hissi olarak geçer" teorisini test ettiğimizde (Bulgular, @tbl-apa-mediation), sayılar bize "anne depresyonu doğrudan çocuğa geçiyor" dedi; ortadaki "ebeveynlik" bir köprü (aracı) görevi görmedi.': 'Maternal depresyonun çocuk algısı üzerindeki etkisinde annenin öz-bildirim tutumlarının aracı (mediator) rol oynadığına dair yapısal eşitlik modeli sınandığında; doğrudan ilişkinin anlamlı bulunduğu, ancak ebeveynlik öz-bildiriminin bir aracı (köprü) işlevi görmediği saptanmıştır (Bulgular, @tbl-apa-mediation).',
        'Ancak bilim insanları (Maxwell ve Cole), bizimki gibi "tek seferlik" anket çalışmalarının bu zincirleme ilişkileri doğru tespit etmekte çoğu zaman yetersiz kaldığını gösterir': 'Ne var ki metodolojik çalışmalar (örn. Maxwell ve Cole) kesitsel (enine) veri yapılarıyla yürütülen dolaylı etki modellerinin zaman içerisindeki aktarımı tespit etmekte kısıtlı kalabileceğini vurgular',
        'Dolayısıyla bu bulguyu "kesinlikle böyle bir geçiş yok" şeklinde değil, "bu geçişi kanıtlamak için aileleri yıllarca izleyen uzun vadeli (boylamsal) çalışmalara ihtiyaç var" şeklinde okumak daha doğru olur': 'Bu nedenle aracılık yokluğu bulgusu salt nedensel bir red olarak değil, kesitsel ölçüm sınırı olarak değerlendirilmeli ve boylamsal tasarımlarla yeniden sınanmalıdır',
        'Anneleri anket cevaplarına göre üç farklı "ebeveynlik profiline" ayırmayı denedik. Psikoloji dünyasında bu tarz profillemeler çok meşhur olsa da, araştırmacıların "kaç profil olmalı" kararını verirken kurallara tam uymadığı bilinmektedir': 'Örneklemdeki annelerin ebeveynlik tutum yanıtları üzerinden üç alt profilli bir gizil sınıflandırma (LPA) denenmiştir. Ancak profil belirleme stratejilerinin istatistiksel geçerliğinin çoğu literatür örneğinde sınırda kaldığı raporlanmaktadır',
        'Biz kendi modelimizde üç grubu istatistiksel testlerle (Bayesçi ölçütler) savunsak da [@nylund2007sinifSayisi], bunu kesin ve değişmez bir yasa gibi değil, ilerideki çalışmaların test etmesi için sunduğumuz bir "ilk taslak" olarak değerlendiriyoruz.': 'Mevcut çözümlemede üç-profilli çözüm fit indeksleriyle [@nylund2007sinifSayisi] desteklense de, bu katmanın doğrulayıcı olmaktan ziyade keşifsel/hipotez-üretici bir model olarak ele alınması uygun olacaktır.',
        'Ebeveynliğin algılanışında, çocuğun kız ya da erkek olmasının bir fark yaratmadığını gördük (Bulgular, §4.4.6). Ancak yaş devreye girdiğinde ilginç bir bulgu ortaya çıkmıştır: Anne yaşlandıkça "aşırı koruma" puanı düşmektedir (p = 0,004). Bu durum, genç ve gelir düzeyi düşük annelerin çocuklarını daha fazla sıkboğaz edebildiği gerçeğiyle birleştiğinde; "aşırı korumanın" diyabet hastalığının kendisine değil, annenin yaşına ve sosyal durumuna bağlı bir refleks olduğunu gösterir': 'Çocuğun cinsiyetinin ebeveynlik algısı üzerinde moderatör etkisi saptanmamıştır (Bulgular, §4.4.6). Yaş değişkeni dikkate alındığında ise, anne yaşı arttıkça aşırı koruma algısının düştüğü görülmüştür (p = 0,004). Düşük ebeveyn yaşı ve düşük sosyoekonomik düzeyin (latent SES) aşırı koruyucu tutumu doğrusal olarak yordaması; bu tutumun doğrudan diyabet tanısından ziyade demografik bağlamın yarattığı adaptif bir refleks olduğuna işaret eder',
        'Araştırmanın zayıf karnını dürüstçe test ettiğimizde şunu gördük: Sağlıklı aileler ile diyabetli ailelerin büyük bir kısmı hastaneye aynı yıl veya dönemde gelmemiştir.': 'Kesitsel çalışmanın temel sınırlılıklarından biri, tanı (diyabet) ve kontrol gruplarının veri toplama dönemlerinin (yıl) zaman ekseninde bütünüyle örtüşmemesidir.',
        'Veriyi sadece \'iki grubun en yoğun olarak bir arada olduğu\' 2023 yılına daralttığımızda, H1\'de bulduğumuz o temel "reddedilmişlik hissi" farkı neredeyse sıfıra inmektedir. Bu durum bize şunu söyler: Bulduğumuz farkın küçük bir bölümü hastalıkla değil, anketlerin farklı yıllarda ve mevsimlerde toplanmış olmasıyla ilgili olabilir': 'Grupların ortak zaman desteğine (overlap) sahip olduğu yalnız 2023 yılı alt-örneklemiyle yürütülen duyarlılık analizinde H1 reddetme ana etkisinin belirgin düzeyde zayıflaması, saptanan grup farkının bir bölümünün dönemsel (period) etkilerden veya karıştırıcı konfounders varyansından kaynaklanabileceğini göstermektedir',
        'O yüzden elde ettiğimiz istatistiksel sonuçlar kavramsal olarak çok tutarlı olsa da, daha büyük ve zamanı denk gruplarla tekrarlanana kadar bu etkinin büyüklüğüne şüphe payı bırakılmalıdır.': 'Bu bağlamda sonuçlar yapısal tutarlılık sunsa da, kesin etkinin doğrulanması için zaman bağlamı eşleştirilmiş eş-zamanlı örneklemlerle yeniden sınama ihtiyacı geçerliliğini korur.',
        'Aynı kronik hastalığı ve aynı evi paylaşsalar bile; anne, sağlıklı kardeş ve diyabetli çocuk ebeveynliği bambaşka şekillerde tecrübe etmektedir. Ebeveynliğe dair potansiyel sorunlar (örneğin reddedilme hissi), annenin anketlerindeki yanıtlarında değil, doğrudan çocuğun algısında gün yüzüne çıkmaktadır. Ancak elimizdeki veriler bu farklılığın "sadece ve kesinlikle diyabetten" kaynaklandığını kanıtlamak için yetersiz kalmıştır.': 'Aynı tıbbi tabloyu ve aynı hanehalkı bağlamını paylaşmalarına rağmen anne, indeks çocuk ve sağlıklı kardeş ebeveynliği fenomenolojik olarak birbirinden oldukça farklı deneyimlemektedir. Reddedilme hissi gibi kritik gelişimsel algı farklılıkları annenin ebeveynlik öz-bildiriminde değil, doğrudan çocuğun değerlendirmesinde ortaya çıkmaktadır. Bununla birlikte, metodolojik sınırlar (kesitsellik, bilgi-verici uyuşmazlığı) göz önüne alındığında, saptanan bu algısal farklılıkların münhasıran diyabet tablosundan kaynaklandığına dair kesin bir nedensel çıkarımdan kaçınılmalıdır.'
    }

    count = 0
    for old, new in replacements.items():
        if old in content:
            content = content.replace(old, new)
            count += 1
            print(f"Replaced: {old[:30]}...")
        else:
            print(f"NOT FOUND: {old[:30]}...")

    with open("chapters/05_tartisma_ve_sonuc.qmd", "w", encoding="utf-8") as f:
        f.write(content)
    
    print(f"Total replaced in ch5: {count}")

process_file()
