import re

def process_file():
    with open("chapters/04_bulgular.qmd", "r", encoding="utf-8") as f:
        content = f.read()

    replacements = {
        'Araştırmada "Acaba annenin depresyonu önce annenin kendi ebeveynlik tutumunu bozuyor, çocuk da bunu mu hissediyor?" şeklinde bir "aracı zincir" test edilmiş ancak bu zincirin çalışmadığı görülmüştür.': 'Anne depresyonunun çocuk algısı üzerindeki etkisinin, annenin ebeveynlik öz-bildirimi üzerinden aracılık (mediation) gösterip göstermediği yapısal bir zincir modeliyle test edilmiş, ancak anlamlı bir dolaylı etki saptanmamıştır.',
        'Başka bir ifadeyle; annenin depresyonunun çocuğu etkilemesi, annenin bildirdiği "reddedici tutumu" üzerinden dolaylı olarak gerçekleşmemektedir.': 'Spesifik olarak, anne depresyonunun çocuk algısı üzerindeki etkisi maternal reddetme öz-bildirimi tarafından aracılık edilmemektedir.',
        'Bu veri belirli bir anın fotoğrafını çektiği için kesin bir "neden-sonuç" kuralı olarak değil, genel bir gözlem olarak okunmalıdır.': 'Kesitsel tasarım sınırlılıkları çerçevesinde bu dolaysız ilişki nedensel bir etki değil, eşzamanlı bir kovaryasyon örüntüsü olarak değerlendirilmelidir.',
        'deprosonun annenin tutumunu etkilediği o ilk "köprü" anlamlı çıkmıştır:': 'depresyonun anne ebeveynlik tutumunu yordadığı a-yolu (aktarımın ilk ayağı) istatistiksel olarak anlamlı bulunmuştur:',
        'Ancak annenin tutumunun çocuğa geçişi olan ikinci köprü anlamsız kalmıştır:': 'Bununla birlikte, anne öz-bildiriminin çocuk algısını yordadığı b-yolu (aktarımın sonuç ayağı) anlamlılık düzeyine ulaşamamıştır:',
        'Bu iki köprünün birleşimi olan zincirleme (dolaylı) etki de sıfırdan farksız bulunmuştur:': 'Buna paralel olarak, a ve b yollarının çarpımından oluşan dolaylı etkinin güven aralığı sıfırı içermiş ve aracılık reddedilmiştir:',
        'Aile içi katmanlı modellerde ve hastalığın durumuna göre yapılan analizlerde de zincirin çalışmadığı teyit edilmiştir.': 'Çok düzeyli aile modellerinde ve diyabet durumuna göre kurgulanan koşullu süreç modellerinde de dolaylı etkinin bulunmadığı çapraz doğrulanmıştır.',
        'Zincirin kopuk olması nedeniyle "dolaylı etki" yerine doğrudan etkilere bakılmıştır. Her üç modelin tamamında (3/3), anne depresyonunun doğrudan çocuğun reddedilme hissini artırdığı (pozitif anlamlı etki) tespit edilmiştir.': 'Aracılığın saptanamaması nedeniyle doğrudan etkilere (c\') odaklanıldığında, üç model spesifikasyonunun tümünde anne depresyonunun çocuktaki reddedilme algısını pozitif ve anlamlı düzeyde öngördüğü görülmüştür.',
        'Ağın genel şekline bakıldığında, diyabetin aile içi iletişim yumağını temelden bozmadığı görülmektedir.': 'Ağ metrikleri genel olarak diyabet durumunun aile içi ilişkisel bağımlılık yapısında köklü bir topolojik değişime yol açmadığını işaret etmektedir.',
        'Okuma anahtarı: Çizgilerin (kenarların) kalınlığı o iki konu arasındaki bağın ne kadar güçlü ve doğrudan olduğunu gösterir. Dairelerin (düğümlerin) büyüklüğü ise o konunun ailenin dinamiğinde ne kadar kilit (merkezî) bir rolde oturduğunu ifade eder.': 'Ağ (network) diyagramı okuma anahtarı: Kenar (edge) kalınlıkları kısmi korelasyon katsayılarının mutlak büyüklüğünü; düğüm (node) boyutları ise değişkenin ağ içindeki merkeziyetini (beklenen etki veya derece) yansıtır.',
        'diyabetin bağların yapısını değiştirmediğini kanıtlamıştır.': 'yapısal ağ eşdeğerliğini koruduğunu doğrulamıştır.',
        'Tahmin doğruluk (kalibrasyon) grafiği: Modelin verdiği \'%X risk\' tahmini ile gerçek hayattaki oranların ne kadar örtüştüğünü gösterir. Okuma anahtarı: Kesikli köşegen çizgi \'kusursuz tahmini\' temsil eder. Noktalar bu çapraz çizgi üzerinde toplanmışsa, modelin tahminleri güvenilir demektir; çizgiden uzaklaşma ise modelin olayları olduğundan daha fazla veya az riskli gördüğüne (yanıldığına) işaret eder.': 'Klinik sınıflandırma kalibrasyon grafiği: Lojistik regresyon modelinin ürettiği tahmini risk olasılıkları (x-ekseni) ile gözlenen depresif eşik insidansı (y-ekseni) arasındaki uyum. Çapraz kesikli çizgi tam kalibrasyonu temsil eder.',
        'Alternatif tahmin modelleri ve değişken önem sıralaması (Yapay Öğrenme Algoritmaları): Anne depresyonunu tahmin ederken hangi bilgilerin (soruların/özelliklerin) daha belirleyici olduğunu makine öğrenimi yöntemleriyle gösterir. Okuma anahtarı: Sağdaki grafikte (Random Forest), çubukların uzunluğu o özelliğin doğru tahmine yaptığı genel katkıyı (önemi) ifade eder. Bu bir neden-sonuç değil, ipucu sırasıdır.': 'Makine öğrenmesi değişken önemlilikleri: Annenin klinik düzey depresyon yükünü kestiren farklı sınıflandırıcıların (sNB, CART, Rastgele Orman, LASSO, XGBoost) duyarlılık profilleri ve algoritmaya özgü Gini safsızlığı azaltım temelli değişken önem sıralaması (VIMP).',
        'Analiz sağlama (çoklu-evren / multiverse) grafiği: Araştırmadaki istatistiksel yöntem, kontrol edilen özellikler ve veri setinde yapılabilecek olası tüm makul değişiklik senaryolarında sonuçların değişip değişmeyeceğini (sağlamlığını) test eder. Okuma anahtarı: Noktaların birikim yönü değişmiyor ve çizginin üstünde veya altında kalmaya devam ediyorsa, farklı hesaplama yöntemleri seçilse bile asıl sonucun/bulgunun değişmeyeceği anlamına gelir. Sonuç: Analiz yöntemi ne kadar değiştirilirse değiştirilsin, tezin ulaştığı asıl sonucun (diyabetin çocuğun algısı üzerindeki etkisi) son derece sağlam ve sarsılmaz olduğu kanıtlanmıştır.': 'Spesifikasyon eğrisi (çoklu evren) grafiği: H1 reddetme algısı ana etkisinin, farklı kovaryat setleri, tahmin algoritmaları, dışlanma kriterleri ve alt örneklemleri içeren 288 eşzamanlı spesifikasyon kombinasyonundaki tespiti. Üst panel etki büyüklüklerini ve %95 güven aralıklarını, alt panel ise modeli kuran kararları gösterir. Sürekli pozitif yöndeki eğri, etki yönünün sağlamlığını (robustness) teyit eder.',
        'Tez sonuçlarının dış dünya (literatür) ile kıyaslanması: Bu araştırmada elde edilen etkilerin (diyabetin ebeveynliğe etkisi), dünyada yapılmış diğer büyük araştırmalardaki (kronik hastalık, anne stresi vb.) etkilerle boyutsal olarak nasıl bir paralellik gösterdiğinin haritasıdır. Okuma anahtarı: Diğer araştırmaların sonuçları yan yana konularak, bu tezde bulunan etkinin diğer hastalık ya da psikolojik stres faktörleriyle benzer veya farklı boyutta olup olmadığı görsel olarak karşılaştırılmıştır. Sonuç: Bu tezin bulduğu etkinin büyüklüğü, dünyada yapılmış olan diğer önemli uluslararası araştırmaların sonuçlarıyla paralel (uyumlu) bulunmuştur.': 'Gözlemsel etkinin dış geçerliği (literatür orman grafiği): Bu tezde H1 reddetme için kestirilen etki büyüklüğünün, kronik hastalık ve ebeveynlik odaklı ana meta-analizlerle karşılaştırması. Bulguların literatürle boyutsal uyumu görselleştirilmiştir.',
        'Yapılan ek incelemeler, annenin \'ben böyle ebeveynlik yapıyorum\' demesi ile çocuğun \'ben böyle ebeveynlik görüyorum\' algısı arasındaki bağın zayıf olduğunu ortaya koymuştur. Annedeki depresyonun, çocuğun olumsuz algısına doğrudan annenin ebeveynlik tutumu aracılığıyla geçmediği anlaşılmıştır. Ayrıca, \'aşırı koruyucu\' davrandığını belirten annelerin genellikle daha genç ve gelir/eğitim düzeyi (sosyoekonomik durumu) daha düşük kişiler olduğu tespit edilmiştir.': 'Tamamlayıcı katman analizleri; anne öz-bildirimi ile çocuk algısı arasındaki aktarımın sınırlı olduğunu doğrulamış ve maternal depresyonun çocuk üzerindeki etkisinde bu öz-bildirimlerin aracı rol oynamadığını teyit etmiştir. Öte yandan, yüksek aşırı koruma bildirimlerinin düşük anne yaşı ve sınırlı sosyoekonomik düzey (latent SES) ile ters yönlü doğrusal ilişkilere sahip olduğu görülmüştür.',
        'Ancak, annenin bu bildirdiği ebeveynlik tutumları ile "çocuğun hissettiği" tutum arasındaki ilişki anlamsız ve çok zayıftır (b değerleri −0,02 ile 0,10 arasında). Dolayısıyla depresyonun, çocuk üzerindeki algıyı "annenin tutumları üzerinden geçerek" dolaylı yoldan etkilemediği, aradaki bağın koptuğu (aracılığın çalışmadığı) istatistiksel güven aralıklarının sıfırı içermesiyle (örneğin sıcaklık [−0,06; 0,02], reddetme [−0,03; 0,02]) ispatlanmıştır.': 'Öte yandan, anne ebeveynlik tutumları ile çocuk algısı arasındaki aktarım (b-yolu) katsayıları zayıf kalmış ve anlamlılığa ulaşmamıştır (b = -0,02 - 0,10). Bu doğrultuda, anne depresyonunun çocuk algısına olası aktarımında anne ebeveynlik öz-bildiriminin istatistiksel bir aracı (mediator) görevi görmediği güven aralıklarının sıfırı içermesiyle kanıtlanmıştır.',
        'Bu durum, hastalık merkezli bir ailede büyümenin kardeş üzerinde her yönden daha yüksek bir "duygusal yoğunluk" (ister iyi ister kötü) yarattığını düşündürür.': 'Bu bulgu örüntüsü, diyabetli ailenin sağlıklı kardeşinde maternal tutumlara yönelik artmış bir algısal duyarlılığa işaret etmektedir.',
        'yani tanı üzerinden çok zaman geçmesi stresi otomatik olarak azaltmamaktadır.': 'dolayısıyla kronolojik uyumlanma varsayımı mevcut veri setinde klinik depresif belirtiler açısından desteklenmemiştir.',
        'Kardeşler arasındaki bağ ne kadar sıcak ve sıkıysa, çocuğun ebeveynlik algısı annenin iddialarıyla o kadar uyumsuz hale gelmektedir': 'İkincil analizlerde, artan kardeş ilişkisi yakınlığının, anne-çocuk ebeveynlik algısı uyuşmazlığını artıran yönde (düşük tutarlılık) düzenleyici etki gösterdiği bulunmuştur',
        'Bu, araları iyi olan kardeşlerin kendi aralarında anneye karşı bir tampon mekanizma kurduklarına dair bir ipucu olabilir.': 'Bu durum, kuvvetli kardeşlik bağlarının ebeveyn etkilerine karşı algısal bir tampon mekanizma oluşturabileceği yönünde yapısal bir işaret sunar.',
        'Bütün bu tablo içerisinde anne, çocuk ve kardeşi gruplara ayırdığımızda (profil analizi), diyabetli ailelerin çoğunlukla "sıcak ve korumacı, yüksek katılımlı aile" profiline düştüğü görülmüştür.': 'Triadik bilgi vericileri (anne, indeks, kardeş) eşzamanlı değerlendiren gizil profil analizi, diyabetli ailelerin kontrol grubuna kıyasla yüksek oranda "kapsayıcı ve katılımlı aile" tipolojisine yüklendiğini göstermiştir.',
        'yani anne "reddetmiyorum" dese bile çocuk bunu diyabet grubunda diğer gruba kıyasla daha derinden hissetmektedir.': 'yani nesnel maternal reddetme seviyesi kontrol edilse dahi, diyabet grubundaki çocuklar reddedilmeyi kontrol grubuna kıyasla daha yüksek bir duyarlılıkla algılamaktadır.',

    }

    count = 0
    for old, new in replacements.items():
        if old in content:
            content = content.replace(old, new)
            count += 1
            print(f"Replaced: {old[:30]}...")
        else:
            print(f"NOT FOUND: {old[:30]}...")

    with open("chapters/04_bulgular.qmd", "w", encoding="utf-8") as f:
        f.write(content)
    
    print(f"Total replaced in exploratory section: {count}")

process_file()
