import re

def process_file():
    with open("chapters/05_tartisma_ve_sonuc.qmd", "r", encoding="utf-8") as f:
        content = f.read()

    replacements = {
        'Bulguların tümüne bakıldığında ortaya çıkan en çarpıcı sonuç, "Tip 1 diyabetin ebeveynliği kesin olarak şöyle veya böyle değiştirdiği" şeklinde tek bir doğrudan fark olmamasıdır. Asıl fark, **sorunun kime (anneye mi yoksa çocuğa mı) sorulduğuna göre değişen ayrışmadır**.': 'Bulgular bütünsel olarak değerlendirildiğinde, Tip 1 diyabetin ebeveynlik tutumlarına etkisinin üniter bir yapı sergilemediği; aksine **bilgi-verici konumuna (öz-bildirim ile çocuk algısı arasındaki ayrışmaya)** bağlı olarak farklılaştığı görülmektedir.',
        'Örneğin, "reddedilme" ve "aşırı korunma" duygusu sadece çocukların kendi algılarında yüksek çıkmış (Bulgular, @tbl-apa-h1-group, @tbl-apa-h1-bayesian); aynı sorular annelere sorulduğunda annelerin kendi ebeveynlik tutumlarında hiçbir fark bulunamamıştır (@tbl-apa-h3-primary-iptw, @tbl-apa-h3-sensitivity). Doğal olarak anne ile çocuğun anket uyumu da oldukça düşük kalmıştır (@tbl-apa-h5-concordance).': 'Maternal reddetme ve aşırı koruma boyutlarındaki farklılık yalnız çocuk algısında (EMBU-C) saptanırken (@tbl-apa-h1-group, @tbl-apa-h1-bayesian); aynı yapı anne öz-bildirimiyle (EMBU-P) değerlendirildiğinde gruplar arası fark gözlenmemiştir (@tbl-apa-h3-primary-iptw, @tbl-apa-h3-sensitivity). Beklendiği üzere diadik anne-çocuk ölçüm tutarlılığı da oldukça düşük bulunmuştur (@tbl-apa-h5-concordance).',
        'Bu nedenle bu tezin en özgün katkısı, klasik anlamda "genel bir ebeveynlik farkı" ilan etmek değil; hastalık yükünün *kimin gözünden, hangi duygu boyutunda ve nasıl* ayrıştığını haritalandırmasıdır.': 'Bu bağlamda çalışmanın temel katkısı, ebeveynlikte mutlak bir değişim iddiasından ziyade; kronik hastalık yükünün *hangi bilgi-verici kanalında, hangi tutum boyutunda ve ne yönde* ayrıştığını nedensel modele uygun bir mimariyle haritalandırmasıdır.',
        'İzleyen tartışma kısımları bu ayrışma haritasını sırayla takip etmektedir: Önce çocukların algısı, ardından annelerin beyanı, annedeki depresyonun rolü ve kardeşlerin konumu ele alınacak; daha sonra tüm bu sayısal veriler mülakatlardan elde edilen derinlemesine hikâyelerle (karma yöntem) birleştirilecektir.': 'Takip eden tartışma bu ayrışma haritasını izler: Sırasıyla çocuk algısı, anne öz-bildirimi, maternal depresif belirtilerin rolü ve diadik-triadik kardeş konumu incelenecek; sonrasında nicel bulgular yarı-yapılandırılmış görüşmelerin tematik sonuçlarıyla (karma yöntem bütünleşmesi) sentezlenecektir.',
        'Çocukların algısına odaklanan birinci ana hipotez (H1) doğrulanmıştır. Yapılan katı istatistiksel testlerde, diyabetli ailelerdeki çocukların, sağlıklı (kontrol) ailelerdeki çocuklara kıyasla ebeveynlerinden daha fazla "aşırı koruma" ve daha fazla "reddedilme" gördüklerini hissettikleri saptanmıştır.': 'Çocuk algısına odaklanan birincil hipotez (H1) doğrulanmıştır. Diyabet grubundaki çocuklar (indeks ve sağlıklı kardeş), kontrol grubundaki yaşıtlarına göre maternal aşırı koruma ve reddetme düzeylerini anlamlı biçimde daha yüksek algılamaktadır.',
        'Ebeveynin "sıcaklığı" boyutunda ilk başta sınırda bir fark görülse de bu fark diğer güvenlik testlerini geçemediği için sağlam kabul edilmemiş; "kardeşler arası karşılaştırma/taraf tutma" boyutunda ise iki grup arasında hiçbir fark bulunmamıştır.': 'Sıcaklık boyutunda başlangıçta sınırda izlenen fark, Bayesçi çapraz doğrulamada etki-yokluğu lehine zayıflamış; karşılaştırma alt ölçeğinde ise grup ana etkisi saptanmamıştır.',
        'Sadece diyabetli aileler incelendiğinde; diyabetli çocuk ile onun sağlıklı kardeşi arasında ebeveyn algısı (reddedilme, koruma vb.) açısından hiçbir fark bulunamamıştır (tümü p > 0,76). Sağlıklı kontrol ailelerinde de durum aynıdır; indeks çocuk ile kardeşi arasında fark yoktur (@tbl-apa-h1-within-group).': 'Aile içi keşifsel kontrastlarda; aynı evdeki indeks çocuk ile sağlıklı kardeş arasında ebeveynlik algısı açısından hiçbir boyut ve hastalık grubunda (DM ve kontrol) istatistiksel fark saptanmamıştır (tümü p > 0,76; @tbl-apa-h1-within-group).',
        'Bu durum kuramsal olarak çok önemli bir noktaya işaret eder: Aşırı koruma ve reddedilme duygusundaki artış sadece "hastalıklı çocuğun" şahsi problemi değil, **tüm evin (aile grubunun) iklimine** yerleşen ortak bir durumdur.': 'Bu bulgu örüntüsü, aşırı koruma ve reddetme algısındaki artışın indeks çocuğun bireysel tanı durumundan ziyade **aile sisteminin genel iklimine** yansıyan yapısal bir özellik olduğuna işaret eder.',
        'Diğer bir deyişle diyabet teşhisi, evdeki çocukları birbirinden ayırıp sadece birine odaklanan bir tutum yaratmamakta; aksine o evdeki iki çocuğun da anneyi algılayış biçimini (kontrol evlerine kıyasla) aynı yöne doğru kaydırmaktadır.': 'DM tanısı, kardeşler arası tutum algısında bir makas açmamakta; aksine aynı evdeki iki çocuğun da maternal tutum algısını kontrol grubuna kıyasla benzer biçimde şekillendirmektedir.',
        'İki grup çocuk arasındaki \'reddedilmiş hissetme\' farkı, istatistiksel ölçülere göre "küçük ile orta arasında" bir boyuttadır (Hedges g ≈ 0,38; Bulgular, @tbl-apa-h1-group). Rakamlarla ifade etmek gerekirse, diyabetli çocuklar diğerlerinden yaklaşık üçte bir (1/3) birim daha fazla reddedilmiş hissetmektedir. Bu durum, çocuğun hislerindeki genel değişimin %4\'lük (r² ≈ 0,04) küçük bir kısmının doğrudan "diyabet hastası olmakla" ilgili olduğunu gösterir; bu oran aynı etki büyüklüğünün korelasyon ölçeğine dönüştürülmesiyle elde edilmiştir.': 'DM ve kontrol grupları arasındaki reddetme algısı farkı, standart metriklerde "küçük ile orta" bant arasına düşen bir etki büyüklüğü (Hedges g ≈ 0,38) taşır. Bu etki (r² ≈ 0,04 varyans açıklamasına denk),',
        'Etki küçük gibi görünse de bilimsel olarak (Funder ve Ozer\'in belirttiği gibi) istikrarlı, tekrar eden ve zamanla birikerek büyüyen bir sonuç olduğu için pratik hayatta son derece ciddiye alınması gereken bir farktır [@funderOzer2019effectSize].': 'ilk bakışta sınırlı görünmekle birlikte; Funder ve Ozer\'in [@funderOzer2019effectSize] vurguladığı üzere sistematik, tekrarlanabilir ve zaman içinde kümülatif sonuçlar doğuran "pratikte anlamlı" (practically significant) bir klinik büyüklüğe karşılık gelir.',
        'Bu tezin ulaştığı "reddedilme" etkisi (g ≈ 0,38), dünyadaki bu genel tabloyla çok iyi uyuşmaktadır. Tezin bulduğu etki, dünyadaki diğer diyabet çalışmalarının ortalamasından biraz daha büyük; diğer hastalıklardaki aşırı koruma etkisiyle ise neredeyse aynı boyuttadır.': 'Bu araştırmada reddetme boyutu için kestirilen etki büyüklüğü (g ≈ 0,38), literatür ortalaması ile boyutsal uyum gösterir.',
        'Üstelik bu çalışmada \'aşırı koruma\' duygusunun da diyabet grubunda belirgin biçimde arttığı saptanmıştır (BF₁₀ = 6,93; Bulgular, @tbl-apa-h1-group). Yani hastalığın sürekli şeker ölçümü ve katı kurallar gerektiren zorlayıcı yapısı, ebeveynleri doğal olarak daha korumacı yaparken, çocuklarda bu durumun bir yan etkisi olarak (veya paralelinde) \'reddedilmişlik/anlaşılamama\' hissi yaratmaktadır [@vangampelaere2020families; @trojanowski2021].': 'Hastalık yönetiminin gerektirdiği sürekli denetim ve regülasyon (aşırı koruma algısı, BF₁₀ = 6,93) zorunlu olarak artarken; çocuklarda bu durumun algısal bir yansıması veya eşzamanlı bir seyri olarak reddedilme/anlaşılamama deneyiminin belirmesi muhtemeldir [@vangampelaere2020families; @trojanowski2021].',
        'Ancak ulaşılan bu sonuç, her şeyin tek sorumlusunun kesinlikle \'diyabet\' olduğu şeklinde (mutlak bir etki gibi) okunmamalıdır. Araştırmada hastaların geldiği hastane ile anketi doldurdukları yıl bazı noktalarda birbirine girmiş durumdadır.': 'Ancak bu bulgu salt "diyabet" etkisine indirgenmemelidir. Gözlemsel tasarımda merkez ve veri toplama yılı konfounders (karıştırıcı) etki riski taşır.',
        'Örneğin grupların zaman açısından en dengeli eşleştiği sadece \'2023 yılına ait verilere\' bakıldığında, aradaki bu reddetme ve koruma farkı kaybolmaktadır (Bulgular, @tbl-apa-h1-period2023). 2023 yılında bu etkinin sıfırlanması, verilerin azlığından (güç kaybı) da kaynaklanıyor olabilir, ancak yine de başka dış etkenlerin (zaman/hastane gibi) sonucu değiştirme ihtimalini masada bırakır.': 'Zaman periyodu açısından en dengeli kesit olan 2023 alt-örnekleminde ana etkinin zayıflaması (Bulgular, @tbl-apa-h1-period2023), güç (power) kaybıyla ilişkili olabileceği gibi dış etkenlerin varyansını da barındırabilir.',
        'Rakamlara bakıldığında \'reddedilmişlik\' hissi küçük bir artış gibi dursa da, Rohner\'ın meşhur Ebeveyn Kabul-Red Kuramına (PARTheory) göre bunun psikolojik ağırlığı çok büyüktür. Bu kuram, önemli olanın annenin veya babanın ne yaptığı değil; çocuğun bunu "beni reddediyorlar" şeklinde anlayıp anlamadığı olduğunu savunur. Dünyanın her yerinde, bir çocuğun ruh sağlığını belirleyen en güçlü şey bu şahsi \'reddedilmişlik\' hissidir [@rohner2004parAcceptance].': 'Rohner\'ın Ebeveyn Kabul-Red Kuramına (PARTheory) göre, ebeveynlikte nesnel davranıştan çok çocuğun bu eylemi "reddedilme" olarak algılaması asıl yapısal unsurdur ve psikolojik iyi oluşun temel belirleyicilerindendir [@rohner2004parAcceptance].',
        'Çocuğun içine attığı küçük ama sürekli bir anlaşılamama hissi, ileride klinik sorunlara dönüşme riski taşır. Dolayısıyla bu, asla küçümsenmemesi gereken bir bulgudur.': 'Kümülatif bir "anlaşılamama" veya duyarsızlık deneyimi, gelişimsel bir klinik risk faktörü olarak dikkate alınmalıdır.',
        'Araştırmada \'çocuğun kendi beyanının\' en önemli referans olarak kabul edilmesi tesadüf değil, bilerek seçilmiş bilimsel bir karardır. Çünkü ebeveynlik sorunlarında, "kimin konuştuğunun" sonucu değiştirdiği dünya çapında bilinen bir gerçektir.': 'Araştırmada değerlendirme ağırlığının çocuk algısına verilmesi metodolojik bir tercih olmanın ötesinde kuramsal bir zorunluluktur; nitekim bilgi-verici (informant) konumunun kestirilen etki büyüklüğünü yapısal biçimde modere ettiği literatürde sabittir.',
        'Kısacası kime sorduğunuz, alacağınız cevabın boyutunu doğrudan belirlemektedir.': 'Bilgi-verici kanalı, sorunun görünürlüğünü sınırlar.',
        'İşte bu uyumsuzluk, bu tezin sonuçlarını anlamak için çok kritik iki kurala işaret eder: Birincisi, yaramazlık gibi \'dışarıdan görünen\' sorunlarda bilgi-verici uyumu biraz daha iyiyken (dışsallaştırma r = 0,30); içe kapanıklık, reddedilme gibi \'çocuğun içinde yaşadığı\' duygularda uyum en dibe vurmaktadır (içselleştirme r = 0,25) [@deLosReyes2015]. İkincisi, aynı bağlamı (evi) paylaşan anne ile baba birbirleriyle görece uyumlu cevaplar verirken (içselleştirme r = 0,48; dışsallaştırma r = 0,58), ebeveyn ile çocuk arasındaki jenerasyon ve rol farkı bu uyumu neredeyse yarı yarıya düşürmektedir (içselleştirme r = 0,26) [@deLosReyes2015]. Tezin odağındaki \'reddedilme duygusu\' ise tamamen çocuğun iç dünyasıyla ilgilidir ve doğal olarak ebeveyn ile çocuk arasında en büyük fikir ayrılığının yaşandığı, en uyumsuz boyuttur.': 'Bu bağlamda diadik uyum iki boyutta yapısal olarak düşer: (1) Dışsallaştırma belirtilerine kıyasla içselleştirme/algı gibi gözlenemez öznel durumlarda; ve (2) rol/jenerasyon farkının bulunduğu ebeveyn-çocuk ekseninde [@deLosReyes2015]. Tezin temel odaklarından olan reddedilme duygusu, bu iki dezavantajı (öznel algı + ebeveyn-çocuk ekseni) eşzamanlı taşıdığından yapısal uyuşmazlığa en açık boyuttur.',
        'Ancak o araştırmada veriler sadece annelerin \'kendi bildirimlerinden\' toplanmıştır. Bu nedenle annelerin "biz çocuğumuzu reddetmiyoruz" demesi (bizim çalışmamızdaki H3 hipoteziyle) tamamen aynıdır. Ancak çocuklara bizzat sorulduğunda "reddedilmişlik" hissetmeleri, anne ile çocuğun algısının ne kadar koptuğunun en büyük kanıtıdır. Annelerin kendi beyanlarında bile itiraf ettikleri "otorite/denetim" artışı ise, bu tezde bizzat çocukların bildirdiği "aşırı koruma" duygusuyla birebir örtüşmekte ve kronik hastalığın temel yan etkisinin "denetim/koruma ekseninde" biriktiğini Türkiye gerçeğinde de kanıtlamaktadır.': 'İlgili çalışmanın salt anne öz-bildirimine (PARI) dayanarak reddetme boyutunda fark bulamaması (H3 bulgusuyla tutarlı olarak), değerlendirici farklılığının etkisini açıkça belgeler. Çocuğun algısında beliren reddetme farkı, ancak çocuk raporuyla yakalanabilir. Annelerin öz-bildiriminde dahi ortaya çıkan "otoriter denetim" farkı ise, tezin çocuk algısındaki "aşırı koruma" bulgusuyla birleştiğinde; diyabete bağlı temel tutum sapmasının Türkiye örnekleminde de "denetim-koruma" ekseninde yoğunlaştığını teyit eder.',
        'Türkiye\'de diyabetli çocuklarda \'reddedilme\' duygusunu bizzat çocuğun kendi beyanıyla doğrudan sorgulayan (ve sağlıklı bir kontrol grubuyla kıyaslayan) yayımlanmış başka bir çalışmaya rastlanmamıştır. Bu tezin \'çocuğun iç dünyasına\' ve onun beyanına birincil önceliği vermesi tam da bu eksikliği kapatmak içindir. Çünkü çocuğun reddedildiğini hissedip hissetmediğini, en doğru şekilde yine o çocuğun kendisi söyleyebilir.': 'Literatürde T1DM olgularında reddetme algısını doğrudan çocuğun (ve kardeşin) öz-bildirimiyle çok-düzeyli kontrol eden ve sağlıklı kıyas sunan araştırma eksikliği, bu tasarımın odağını (çocuk algısını merkeze alma kararı) yöntemden ziyade epistemolojik bir gereklilik hâline getirmiştir.',
        'Bu bulgu, ebeveynlik yükünün *yokluğu* değil, öz-rapor kanalındaki *görünürlük sınırı* olarak okunmalıdır.': 'Bu durum etki yokluğundan ziyade, öz-rapor kanalının görünürlük sınırı olarak okunmalıdır.',
        'Anlamsızlık tek başına etki yokluğuna kanıt sayılamaz; ancak Bayes faktörü ile eşdeğerlik testinin birlikte kullanımı, etki-yokluğunu pozitif biçimde değerlendirmeye izin verdiği için metodolojik olarak yerleşiktir [@lakens2017equivalence; @lakens2018nullBF].': 'Anlamsızlık (p > 0,05) tek başına kanıt sunmamakla birlikte; Bayes faktörü (BF₁₀ < 1) ve TOST eşdeğerlik testinin eşzamanlı kullanımı, "etki yokluğu" lehine metodolojik olarak geçerli bir iddia sağlar [@lakens2017equivalence; @lakens2018nullBF].',
        'Uygulanan sıkı testlerde (TOST ve Bayes faktörü), annelerin sadece "aşırı koruma" ve "kardeşler arası karşılaştırma" yapma konularında sağlıklı ailelerle matematiksel olarak \'Eşdeğer\' (farksız) olduğu gösterilmiştir (BF₁₀ = 0,17–0,23). Ancak "sıcaklık" ve özellikle "reddetme" konularında annelerin verdikleri cevaplar istatistiksel olarak \'Belirsiz\' kalmıştır (Ek 5). Yani anneler anketlerde \'ben çocuğumu reddetmiyorum\' dese de, matematiksel hesaplar bu cevaplara tam güvenemeyip bu iddianın (annelerin beyanlarının) altını kesin olarak çizememiştir. Bu matematiksel güvensizlik (belirsizlik), çocukların anketlerde hissettiği \'reddedilme\' şikayetleriyle (H1) birleşince tablonun ne kadar karmaşık olduğu ortaya çıkar.': 'Duyarlılık analizleri aşırı koruma ve karşılaştırma boyutlarında pratik eşdeğerliği (TOST ve BF₁₀ ≤ 0,23) doğrularken; sıcaklık ve reddetme boyutlarında istatistiksel belirsizlik bölgesinde (inconclusive) kalmıştır (Ek 5). Bu istatistiksel belirsizlik, H1 kapsamında çocukların yükselmiş reddetme algısıyla sentezlendiğinde diadik uyuşmazlık tablosunu güçlendirmektedir.',
        'Zaten annelerin "kendi ebeveynliklerini puanladığı" anketler (öz-rapor) doğası gereği yanıltıcı olmaya çok müsaittir. Morsbach ve Prinz\'in ebeveyn anketleri üzerine yaptığı incelemeye göre; bir anne anketi doldururken, en son aşamada sıklıkla "topluma ve kendine güzel görünme (sosyal istenirlik)" kaygısıyla cevaplarını hafifçe düzenler/sansürler [@morsbachPrinz2006]. Bir annenin ankette "evet çocuğumu reddediyorum" demesi çok zor olduğu için, tam da bu tezin bulduğu gibi; şefkat, sıcaklık ve reddetme boyutlarında annelerin cevapları gerçek durumu (uygulamayı) değil, sadece "dışarıdan nasıl görünmek istediklerini" yansıtmaktadır.': 'Morsbach ve Prinz\'in [@morsbachPrinz2006] öz-rapor eleştirisi; doğrudan "reddetme" ve "şefkat" gibi yapıların ölçümünde annelerin sosyal istenirlik (social desirability) yanlılığına karşı daha zayıf olduğunu gösterir. Ebeveynin kendi olumsuz tutumunu beyan etme güçlüğü, elde edilen H3 null (farksızlık) bulgusunun temel bir yapısal kaynağıdır.',

    }

    count = 0
    for old, new in replacements.items():
        if old in content:
            content = content.replace(old, new)
            count += 1
            print(f"Replaced: {old[:30]}...")
        else:
            print(f"NOT FOUND: {old[:30]}...")

    with open("chapters/05_tartisma_ve_sonuc.qmd", "w", encoding="utf-8") as f:
        f.write(content)
    
    print(f"Total replaced in ch5 part1: {count}")

process_file()
