import re

def process_file():
    with open("chapters/05_tartisma_ve_sonuc.qmd", "r", encoding="utf-8") as f:
        content = f.read()

    replacements = {
        'Annenin hissettiği depresyon (ruhsal çöküntü) yükü ile kendi ebeveynlik tutumu arasındaki ilişkiye odaklanan dördüncü ana hipotez (H4) kısmen doğrulanmıştır. Yapılan matematiksel modellemede, annenin depresyonu arttıkça ebeveynlik tarzının dört boyutundan üçünün (sıcaklık, reddetme, karşılaştırma) olumsuz etkilendiği görülmüştür (Bulgular, @tbl-apa-h4-sem). Ancak modelin bütünsel uyum gücü (CFI/TLI vb.) istatistiksel eşiklerin altında kaldığı için, bu sonuçlar "depresyon kesin olarak şu ebeveynliğe yol açar" şeklinde kesin bir neden-sonuç mekanizması olarak değil; sadece "bu iki durum aynı anda kötüleşme eğiliminde" şeklinde okunmalıdır.': 'Anne depresif belirti yükü ile ebeveynlik öz-bildirimi arasındaki yapısal ilişkiyi sınayan dördüncü hipotez (H4) kısmen desteklenmiştir. Yapısal eşitlik modelinde, yüksek maternal depresyonun düşük sıcaklık, artmış reddetme ve artmış karşılaştırma tutumlarını istatistiksel olarak anlamlı düzeyde yordadığı gösterilmiştir (Bulgular, @tbl-apa-h4-sem). Bununla birlikte karşılaştırmalı uyum indekslerinin (CFI, TLI) marjinal kalması ve tasarımın kesitsel doğası gereği, saptanan bu bağlar nedensel bir etki yönünden ziyade eşzamanlı bir kovaryasyon örüntüsü olarak yorumlanmalıdır.',
        'Bu ilişkinin yönü ve büyüklüğü, dünya çapındaki diğer büyük araştırmalarla tam uyum içindedir. Örneğin Lovejoy ve arkadaşlarının 46 çalışmayı birleştirdiği analizinde; annedeki depresyonun en çok "olumsuz/düşmanca ebeveynlik" ile (r = −0,44) bağlantılı olduğu bulunmuştur. Annenin olumlu davranışları (sıcaklık gibi) ise depresyondan çok daha az etkilenmektedir [@lovejoy2000maternal]. Bu tezde de annenin depresyonu arttığında şefkatin/sıcaklığın azalmasından ziyade, \'reddetme\' tutumunun çok daha sert bir şekilde artması, dünyadaki bu eğilimle birebir örtüşmektedir.': 'Örüntünün yönü ve görece büyüklüğü literatürle tutarlıdır. Lovejoy ve arkadaşlarının [@lovejoy2000maternal] 46 çalışmalık meta-analizinde anne depresyonu en güçlü negatif etkiyi olumsuz/düşmanca ebeveynlik davranışı (d = 0,44) üzerinde gösterirken, olumlu davranışlar üzerindeki etki daha zayıf (d = -0,16) kalmıştır. Mevcut tezde saptanan, anne depresyonunun pozitif boyutlardan (sıcaklık) ziyade olumsuz/kontrol edici boyutlarda (reddetme ve karşılaştırma) daha keskin yapısal yollar (path coefficients) üretmesi, bu bulguyla paraleldir.',
        'Yine Goodman ve ekibinin 80 binden fazla anne-çocuğu incelediği devasa çalışmada, depresyon ile ebeveynlik arasındaki ilişkinin aslında rakamsal olarak küçük (r = 0,23 civarı) olduğu bulunmuştur. İşin ilginç yanı, annelerin anketlerde (kendi beyanlarında) bu etkiyi gereğinden fazla şişirme eğiliminde olmasıdır [@goodman2011maternalMetaanalytic]. Bizim araştırmamızda çıkan sonuçların da tam bu sınırda kalması, annelerin "kendilerine dair anketleri doldururken" (H3) yanıltıcı bir tablo çizebileceği uyarımızı destekler. Depresyonun ebeveynliği etkilediği gerçeği, uzun yıllar süren takiplerle de (r = 0,15) ayrıca gösterilmiştir [@goodman2020parentingMediator].': 'Goodman ve ekibinin [@goodman2011maternalMetaanalytic] devasa meta-analizinde anne depresyonu ile ebeveynlik arası ilişki küçük-orta bantta (r ≈ 0,23) tespit edilmiş, ancak bu bağın öz-bildirim araçlarında daha güçlü saptanması yöntem varyansına (method variance) bağlanmıştır. Tezin saptadığı ilişkilerin bu bantta kalması bu bulguyu desteklerken, boylamsal çalışmalarda depresyon-ebeveynlik bağının (r = 0,15) korunması yapısal etkinin varlığını teyit eder [@goodman2020parentingMediator].',
        'Daha da önemlisi, annenin hissettiği depresyon sadece kendi psikolojisinde kalmamakta, çocuğun algısına doğrudan sıçramaktadır. Bu çalışmada (keşifsel ikincil çözümlemelerde); depresyon testinden yüksek (Beck ≥ 17) puan alan annelerin çocukları, -hastalıktan veya annenin ilaç kullanıp kullanmamasından bağımsız olarak- kendilerini bariz biçimde daha fazla \'reddedilmiş\' (p = 0,004) ve diğer çocuklarla \'kıyaslanmış\' (p = 0,003) hissettiklerini beyan etmiştir (Bulgular, "[KEŞİFSEL · İKİNCİL] İleri Psikometrik ve Bağlamsal Katman"). Bu bulgu, H4 (annenin depresyonu) ile H1 (çocuğun reddedilme hissi) arasındaki kayıp köprüyü kurar. Annenin ruhsal sıkıntısı anketlerdeki kendi beyanına yansımasa bile, çocuğun omuzlarına \'reddedilmişlik hissi\' olarak doğrudan çökmektedir [@goodman1999risk].': 'Dahası maternal depresif yük öz-bildirim boyutunda sınırlı kalmamakta, çocuk algısına doğrudan geçişkenlik göstermektedir. İkincil keşifsel katmanda, yüksek klinik belirti gösteren (Beck ≥ 17) annelerin çocukları, hastalık durumundan ve aktif antidepresan kullanımından bağımsız olarak belirgin düzeyde yüksek maternal reddetme (p = 0,004) ve karşılaştırma (p = 0,003) algısı bildirmiştir. Bu bulgu, H4 (maternal depresyon) ile H1 (çocuk reddetme algısı) arasındaki algısal yansımayı açıklar: annenin beyanından bağımsız biçimde maternal psikiyatrik sıkıntı çocuğun değerlendirmesine yansımaktadır [@goodman1999risk].',
        'Kısacası, anne \'ben sıcak bir anneyim\' dese de önemli olan çocuğun bunu nasıl hissettiğidir.': 'Bu bağlamda ebeveyn öz-bildiriminden ziyade çocuğun ebeveynlik algısı klinik gelişimi şekillendiren temel faktördür.',
        'Modelde \'aşırı koruma\' ile depresyon arasında bir bağ bulunamaması ise aslında bir çelişki değil, çok değerli bir ipucudur. Çünkü diyabetli bir ailede aşırı korumacılık, annenin depresyonundan değil doğrudan \'hastalığın kendisinden\' kaynaklanmaktadır [@pinquart2013]. Yani anne depresyonda olmasa bile, hastalığın zorunlu kuralları (şeker takibi vb.) anneyi aşırı korumacı yapmaktadır. Öte yandan, 1.435 çalışmayı inceleyen dev meta-analizde gösterildiği gibi, reddetme veya sert kontrol gibi özellikler doğrudan çocuğun psikolojisini bozan dışa vurumlarla (hırçınlık vb.) ilişkilidir [@pinquart2017parentingDimensions].': 'Aşırı koruma ile depresyon arasında anlamlı bir yapısal yol (path) saptanamaması, bu boyutun psikiyatrik yükten bağımsızlaştığını gösterir. Kronik hastalık bağlamında aşırı koruma, depresif bir semptom uzantısından ziyade hastalık yönetiminin (glisemik kontrol, rejim uyumu) nesnel gereklerine karşı üretilen durumsal ve adaptif bir tutumdur [@pinquart2013]. Reddetme gibi sert tutumların aksine [@pinquart2017parentingDimensions], aşırı korumanın bu bağlamda içselleştirilmiş bir düşmanlıktan çok tıbbi izlemin yapısal bir zorunluluğunu yansıtması muhtemeldir.',
        'Bütün bu ilişkiler yorumlanırken araştırmanın anlık bir kesit (fotoğraf) olduğu unutulmamalıdır. Tek bir seferde toplanan verilerle "annenin depresyonu çocuğun reddedilme hissini yaratır" diyemeyiz, sadece "bu iki durum aynı anda, el ele kötüleşir" (eş-değişim) diyebiliriz [@maxwellCole2011crossMediation]. Bu sebeple nedensel bir risk aktarımı iddiasında bulunulmamıştır.': 'Enine kesitsel veride nedensel yönelim kurulamayacağı göz önüne alındığında, depresyon ve ebeveynlik arasındaki ilişkinin salt eş-değişim (covariation) olarak okunması metodolojik bir gerekliliktir [@maxwellCole2011crossMediation].',

    }

    count = 0
    for old, new in replacements.items():
        if old in content:
            content = content.replace(old, new)
            count += 1
            print(f"Replaced: {old[:30]}...")
        else:
            print(f"NOT FOUND: {old[:30]}...")

    with open("chapters/05_tartisma_ve_sonuc.qmd", "w", encoding="utf-8") as f:
        f.write(content)
    
    print(f"Total replaced in ch5 part2: {count}")

process_file()
