import re

def process_file():
    with open("chapters/04_bulgular.qmd", "r", encoding="utf-8") as f:
        content = f.read()

    replacements = {
        # H2 cont.
        'Öncelikle her evdeki iki kardeşin anket puanlarının ortalaması alınarak aile düzeyinde bir değerlendirme yapılmıştır (241 aile üzerinden). Bu analizde gruplar arasındaki fark, istatistiksel açıdan "çok küçük" (etki büyüklüğü d < 0,20) kalmıştır.': 'Kardeş ortalamaları üzerinden yürütülen aile düzeyi analizde, tüm boyutlarda gruplar arası fark etki büyüklüğü açısından önemsiz kalmıştır (d < 0,20).',
        'İkinci olarak, evdeki bir çocuğun kardeş algısının diğer çocuğu da etkileyeceği gerçeğinden yola çıkılarak kardeşlerin birbirlerine olan etkileri hesaplanmış (karşılıklı bağımlılık modeli) ve burada da gruplar veya çocukların rolü (hasta ya da sağlıklı olması) açısından bir fark bulunamamıştır (p > 0,350).': 'İkinci olarak, kardeşler arası diadik bağımlılığı denetleyen aktör-partner karşılıklı bağımlılık modeli (APIM) sonuçlarında da diyabet durumu veya hastalık rolü ana etkisi saptanmamıştır (p > 0,350).',
        'Son olarak, doğrudan anket puanları yerine, bu puanların altındaki gerçek yapıyı matematiksel olarak ayrıştıran özel bir modelle (Olsen-Kenny düad modeli) kardeşlerin kavga/çatışma davranışları incelenmiştir. Bu gizli (latent) bağ analizinde, kardeşler arasındaki çatışma algısının r = 0,27 düzeyinde pozitif bir ilişki (korelasyon) gösterdiği bulunmuştur; yani bir kardeş çatışma bildirdiğinde, diğeri de benzer oranda çatışma bildirme eğilimindedir. Dikkat çekici olan, bu karşılıklı ilişkinin çocukların her ikisinin de aynı veya farklı cinsiyette olmasına ya da aralarındaki yaş farkının büyüklüğüne göre bir değişim göstermemiş olmasıdır.': 'Gizil düzeyde yürütülen Olsen-Kenny modeli çatışma boyutunda r = 0,27 düzeyinde anlamlı bir diadik uyum göstermiştir; bu bağımlılık yapısı cinsiyet kompozisyonu (aynı/farklı) ve kardeşler arası yaş farkından etkilenmemiştir.',
        'Farkın "hiç olmadığını" doğrudan kanıtlayan özel bir istatistiksel yöntem (eşdeğerlik testi - TOST), araştırmanın başında planlanmadığı için sonradan kullanılmamış, bu sebeple sonuç bilimsel bir dille "fark yoktur" şeklinde değil "farkın varlığına dair yeterli kanıt yoktur" şeklinde ifade edilmiştir': 'Bu boyutta ön-kayıtlı bir eşdeğerlik sınaması planlanmadığından, p-değeri temelli "farkın gösterilememesi" durumu nedensel bir "etki yokluğu" yerine istatistiksel belirsizlik olarak raporlanmıştır',
        'Aile ortalamaları ile yapılan testlerin sonuçları @tbl-apa-h2-family-mean içinde, kardeşlerin birbirini nasıl etkilediğinin (aktör/partner modeli) sayısal verileri @tbl-apa-h2-apim içinde ve bunun görsel haritası ise @fig-h2-apim-path içinde sunulmuştur.': 'Aile ortalamalarına dayalı bulgular @tbl-apa-h2-family-mean, diadik APIM modelleri @tbl-apa-h2-apim ve bunlara ait yol haritaları @fig-h2-apim-path üzerinde özetlenmiştir.',
        'H2 kardeş ilişkisi aile ortalamaları tablosu: Kardeş ilişkisinin dört boyutunda (yakınlık, güç, çatışma, rekabet), her ailedeki iki kardeşin puanlarının ortalaması alınarak diyabetli aileler ile kontrol aileleri (toplam 241 aile) karşılaştırılmıştır. Tabloda grupların değerleri, yapılan istatistiksel testin (Welch t) sonucu ve ortaya çıkan farkın büyüklüğü (Cohen d) verilmiştir. Okuma anahtarı: Farkın büyüklüğünü gösteren \'d\' değerinin 0,20\'nin altında olması, var olan farkın pratikte \'çok küçük / önemsiz\' kabul edildiğini gösterir.': 'H2 kardeş ilişkisi aile ortalamaları: KİA\'nın dört alt ölçeği üzerinden elde edilen aile-düzeyi (kardeş ortalamaları) diyabet-kontrol karşılaştırması. Bulgular ortalama, Welch t-testi istatistiği ve Cohen d etki büyüklüğü ile sunulmuştur; |d| < 0,20 değeri önemsiz (negligible) etki bandına karşılık gelir.',
        'H2 kardeşlerin karşılıklı etkileşim modeli (APIM): Evdeki iki kardeşin ilişki algısı birbirinden bağımsız değildir. Bu model, \'benim düşüncem kendi sonucumu nasıl etkiliyor\' (aktör etkisi) ile \'kardeşimin düşüncesi benim sonucumu nasıl etkiliyor\' (partner etkisi) durumlarını birbirinden ayırarak inceler. Tabloda diyabet/kontrol grubu, çocuğun hasta/sağlıklı rolü ve bunların birbirleriyle olan etkileşimine dair güven aralıkları verilir. Okuma anahtarı: Bir değerin %95 güven aralığı sıfırı kapsıyorsa, bu o sonucun istatistiksel olarak sıfırdan ayırt edilemeyeceği, yani anlamlı bir etki olmadığı anlamına gelir.': 'H2 aktör-partner karşılıklı bağımlılık modeli (APIM): Kardeş değerlendirmelerindeki diadik bağımlılığı çözümleyen yapısal model. Kendi bildiriminin kendi sonucuna etkisi (aktör) ile kardeş bildiriminin kendi sonucuna etkisi (partner) ayrıştırılmıştır; tabloda grup ve rol etkileşim katsayıları ile %95 güven aralıkları raporlanmıştır.',
        'H2 kardeş etkileşimi (APIM) yol haritası: Kardeş İlişkileri Anketi\'ne (KİA / SRQ) verilen yanıtlarda, diyabetli çocuk ile sağlıklı kardeşin birbirini nasıl etkilediğini gösteren diyagramdır. Düz oklar kişinin kendi düşüncesinin kendisini (aktör) veya kardeşinin düşüncesinin kendisini (partner) nasıl etkilediğini gösterir. Çift yönlü kavisli çizgiler ise bir etki veya neden-sonuç değil, iki durumun birlikte nasıl hareket ettiğini (korelasyonunu) temsil eder.': 'H2 APIM yol diyagramı: Diadik veri yapısındaki aktör (düz yatay oklar) ve partner (düz çapraz oklar) etkileri ile bağımsız değişkenler (yaş farkı, cinsiyet uyumu) ve hata terimleri arası korelasyonları (çift yönlü kavisli oklar) gösteren kavramsal model.',

        # H3
        'Annelerin kendi ebeveynlik tutumları hakkındaki değerlendirmelerinde (sıcaklık, aşırı koruma, reddetme ve karşılaştırma), diyabetli çocuk anneleri ile kontrol grubu anneleri arasında anlamlı bir fark bulunmamıştır. Bu "fark yokluğu" sonucu, pek çok farklı analiz yöntemiyle doğrulanmıştır. Ancak hatırlanacağı üzere çocukların kendi değerlendirmelerinde (H1) annelerinden reddedilme algılarında bir farklılık çıkmıştı; annelerin kendi bildirimlerinde böyle bir fark çıkmaması, anne ile çocuğun ebeveynlik tutumunu farklı algıladığını gösteren ilgi çekici bir çelişkidir. Annenin tutumunda böyle bir farkın görülmeyip çocukların algısında görülmesi tartışma bölümünde ele alınmıştır.': 'Annelerin öz-bildirimle değerlendirdiği dört ebeveynlik tutumunda (sıcaklık, aşırı koruma, reddetme, karşılaştırma) diyabet ve kontrol grupları arasında istatistiksel olarak anlamlı bir farklılık saptanmamıştır. Bu bulgu çoklu duyarlılık analizleriyle doğrulanmıştır. H1 (çocuk algısı) bulgularındaki grup farklılıklarının anne öz-bildiriminde görülmemesi, değerlendiriciler arası uyuşmazlığa işaret etmekte olup tartışma bölümünde yapısal bir fenomen olarak ele alınmıştır.',
        'Ham verilerle yapılan karşılaştırmalarda diyabetli anneler ile kontrol anneleri arasında sıfırdan ayırt edilebilir bir farka rastlanmamıştır (p > 0,500).': 'Çoklu karşılaştırma (BH-FDR) düzeltmeli birincil ANCOVA modelinde hiçbir alt ölçekte grup ana etkisi sıfırdan ayırt edilememiştir (p > 0,500).',
        'Bu sonuç, sonradan aileler arası eşitsizlikleri düzelten daha gelişmiş istatistiksel bir ağırlıklandırmayla (IPTW) test edildiğinde de değişmemiştir (p > 0,510). Dahası; annesi antidepresan kullanan aileler (n = 46) kendi içlerinde özel olarak incelendiğinde de sonuç değişmemiş, bulgunun anne psikolojisindeki farklılıklardan kaynaklanmadığı doğrulanmıştır.': 'Gözlemsel karıştırıcıları denetleyen eğilim skoru ağırlıklandırması (IPTW) sonrasında da bulgu deseni değişmemiştir (p > 0,510). Annenin aktif antidepresan kullanımı bağlamında yapılandırılan alt grup duyarlılık analizinde de grup farkı yokluğu korunmuştur.',
        'Klasik yöntemlerin ötesinde bağımsız bir doğrulama yöntemi olarak kullanılan Bayesçi analiz de, gruplar arasında bir fark *olmadığına* dair güçlü (H0 lehine) kanıtlar sunmuştur. Ayrıca, aradaki farkın uygulamada hiçbir önem taşımayacak kadar küçük olduğunu gösteren eşdeğerlik testi (TOST) de, annelerin verdikleri cevapların temelde "eşdeğer" olduğunu ya da birbirlerinden ayırt edilemeyecek kadar yakın olduğunu göstermiştir': 'Bayesçi analizler tüm alt ölçekler için "etki yokluğu" (H0) yönünde güçlü kanıt (BF₁₀ < 1) sunmuştur. Buna ek olarak TOST istatistiksel eşdeğerlik sınaması, diyabet ve kontrol grubu annelerinin ebeveynlik puanlarının önceden tanımlanmış eşdeğerlik bandı (|SMD| < 0,30) içinde yer aldığını kanıtlamıştır',

        # H4
        'Annedeki depresyon belirtileri arttıkça, annenin çocuğuna gösterdiğini belirttiği "sıcaklık" azalmakta; buna karşılık "reddetme" ve "karşılaştırma" tutumları artmaktadır. İstatistiksel olarak ortaya konan bu ilişki, çalışmanın ölçüm yöntemi (zaman içindeki takibi değil, tek bir andaki fotoğrafı çekmesi) nedeniyle kesin bir "neden-sonuç" ilişkisi olarak değil, bu iki durumun "birlikte değiştiği" yönünde yorumlanmalıdır. İstatistiksel model mükemmel bir uyum göstermediği için ulaşılan sonuç kesin bir kuraldan ziyade bu grubun genel bir gözlemi olarak okunmalıdır.': 'Anne depresif belirti yükü; azalan ebeveyn sıcaklığı, artan reddetme ve artan karşılaştırma tutumlarıyla istatistiksel olarak anlamlı biçimde ilişkilendirilmiştir. Bu yapısal bağlar enine kesitsel bir tasarımla elde edildiğinden nedensel bir yönelim değil, kovaryasyon örüntüsü yansıtır. Yapısal eşitlik modelinin uyum indekslerindeki kısıtlılıklar nedeniyle bulguların genellenebilirliği ihtiyatla değerlendirilmelidir.',
        'Dört ilişki yolundan üçü istatistiksel olarak anlamlı çıkmıştır: Depresyon puanı arttıkça, sıcaklığın düştüğü (β = −0,28), reddetmenin (β = 0,33) ve karşılaştırmanın (β = 0,28) arttığı görülmüştür (hepsi için p < 0,001). Aşırı korumada ise artış yönünde bir eğilim olsa da bu sonuç istatistiksel olarak anlamlı bulunmamıştır.': 'Test edilen dört yapısal yoldan üçü anlamlı bulunmuştur: Yüksek depresif belirtiler düşük sıcaklık (β = −0,28), yüksek reddetme (β = 0,33) ve yüksek karşılaştırma (β = 0,28) ile öngörülmüştür (tümü için p < 0,001). Aşırı koruma boyutuyla depresyon arasındaki ilişki istatistiksel anlamlılığa ulaşmamıştır.',
        'hata oranları (RMSEA) düşük olsa da genel uyum eşiklerinin bilimsel olarak istenen altın standartların tam anlamıyla karşılanmadığı görülmüştür. Bu yüzden sonuçları aktarırken "depresyon reddetmeye yol açar" gibi iddialı bir neden-sonuç dili yerine "depresyon ve reddetme birlikte görülmektedir" dili tercih edilmiştir. Modelin diyabetli ve kontrol ailelerinde aynı şekilde çalışıp çalışmadığına bakıldığında büyük ölçüde iki grubun da bu kuralları (depresyon-tutum ilişkisini) adil ve benzer biçimde yaşadığı doğrulanmıştır.': 'RMSEA yeterli görünse de karşılaştırmalı uyum indeksleri (CFI, TLI) marjinal düzeyde kalmıştır. Ölçüm değişmezliği analizlerinde yapısal ağırlıklar modelinin diyabet ve kontrol grupları arasında kısmi değişmezlik sağladığı doğrulanmış, böylelikle raporlanan örüntünün her iki grup için de benzer yapıda işlediği teyit edilmiştir.',

        # H5
        'Aynı evde yaşayıp aynı ilişkiyi deneyimlemelerine rağmen, "anne" ile "çocuğun" ebeveynlik tutumlarına verdikleri cevaplar arasındaki uyum oldukça düşüktür. Yani ebeveynlik ilişkisini anne farklı bir pencereden, çocuk bambaşka bir pencereden algılamakta; ikisi birbiriyle uzlaşamamaktadır. Ulaşılan bu uyumsuzluk, analiz edilen dört alt alanın (sıcaklık, koruma, reddetme, karşılaştırma) tamamında net biçimde görülmüştür. Dahası; diyabetli ailelerdeki anne-çocuk anlaşmazlığı ve uyumsuzluğu, kontrol ailelerindekine kıyasla bazı tutumlarda daha da belirgindir (yani kontrol grubunda uyum diyabete kıyasla nispeten daha yüksektir).': 'Anne öz-bildirimi ile çocuk algısı arasındaki diadik tutarlılık (uyum) tüm ebeveynlik boyutlarında oldukça zayıf saptanmıştır. Daha önemlisi, diyabetli ailelerdeki diadik uyumsuzluk örüntüsü, sağlıklı kontrol grubuna göre sistemli biçimde daha yüksektir (kontrol ailelerindeki uyum diyabete kıyasla daha korunmuştur).',
        'Anne ile çocuk arasındaki ilişkinin bu iki cepheden nasıl göründüğü (uyum), beş farklı ve karmaşık istatistiksel yöntemle incelenmiştir. Her bir yöntem uyumun farklı bir cephesine bakar: puanların birebir tutarlılığı, uyumsuzluğun bir yüzey haritasındaki yeri, ailenin ortak dokusu vb. Araştırma başlamadan önce belirlenen kurala göre, diyabet ve kontrol grupları arasında "net bir fark" olduğunun söylenebilmesi için bu beş yöntemden en az üçünün aynı yönü işaret etmesi gerekmiştir. Sonuçlar şu şekildedir:': 'Bu diadik ayrışma; mutlak puan farkı, yanıt yüzeyi topolojisi ve gizil varyans ortaklığına odaklanan beş bağımsız stratejiyle analiz edilmiştir. Ön-kayıtlı karar kuralı uyarınca, gruplar arası uyum farkı iddiası için en az üç stratejinin yakınsaması (convergence) aranmıştır:',
        'Anne ile çocuğun verdiği ham anket puanlarının ne kadar örtüştüğüne bakılmıştır. Bu yöntemle ölçülen tutarlılık puanı 0,00 ile 0,10 arasında çok düşük çıkmıştır; bu bilimsel eşiklerde "zayıf/yetersiz uyum" anlamına gelir. Hatta diyabetli ailelerde puanlar sıfırın altına bile inmiştir (yani anne ile çocuğun verdiği yanıtlar birbirinden tamamen kopuktur). Genel olarak kontrol grubundaki anne-çocuk tutarlılığı, diyabetli gruba göre tüm alt başlıklarda (sıcaklık, koruma, reddetme, karşılaştırma) daha yüksektir. Uyum oranlarının görsel haritası @fig-h5-bland-altman içinde sunulmuştur.': 'Mutlak puan uyumunu test eden ICC değerleri tüm boyutta 0,10\'un altında kalarak zayıf tutarlılığa işaret etmiştir; DM grubunda katsayılar yer yer sıfırın altına (negatif değerlere) inmiştir. Dört boyutun tamamında kontrol grubundaki dyad tutarlılığı DM grubundan yüksektir (@fig-h5-bland-altman).',
        'Annenin ve çocuğun puanlarının nasıl farklılaştığını ve bunun annenin depresyonuyla olan ilişkisini bir "3 boyutlu harita" gibi çizen bu yöntemde, çok ilginç bir bulgu ortaya çıkmıştır: Diyabetli grupta, anne ile çocuğun reddetme algısı zıtlaştıkça (örneğin anne "çocuğumu reddetmiyorum", çocuk ise "annem beni reddediyor" dedikçe) annenin depresyon skoru belirgin biçimde artmaktadır. Bu örüntü sağlıklı kontrol grubunda hiç görülmemiştir. İlgili haritalar @fig-h5-rsa-surface içinde yer almaktadır.': 'Bireysel puan sapmalarının yönünü üçüncü bir sonuç değişkeniyle (anne depresyonu) topolojik olarak ilişkilendiren yanıt yüzeyi analizinde; diyabetli ailelerde anne-çocuk reddetme uyuşmazlığı derinleştikçe anne depresif belirtilerinin doğrusal olmayan biçimde arttığı (b₁ ve a₄ parametreleri) saptanmıştır. Kontrol grubunda bu zıtlaşma-depresyon örüntüsü gözlenmemiştir (@fig-h5-rsa-surface).',
        'Aile bireylerinin "ortak tek bir aile ruhu" etrafında toplanıp toplanmadığına bakılmıştır. Sıcaklık dışında, reddetme ve karşılaştırmada bu "ortak doku" puanları o kadar düşüktür ki, istatistiksel sistem hatası vermiştir. Diyabetli ailelerin "ortak doku/uyum" puanı kontrol ailesinden de düşüktür; bu da diyabetli ailelerde "tek ve ortak bir tutum/algı" varsayımının geçersiz olduğunu kanıtlar.': 'Dyad üyelerinin ortak bir gizil ebeveynlik faktörü etrafında kümelenme kapasitesi incelenmiştir. Sıcaklık dışındaki boyutlarda ortak faktör varyansı çözümlenemeyecek kadar düşük çıkmış; DM grubunda kontrol grubuna kıyasla daha düşük ortak faktör yükleri (non-convergence) gözlenmiştir.',
        'Testlerin kendi ölçüm hataları matematiksel olarak temizlenip aradaki "saf ilişkiye" bakıldığında; kontrol grubundaki anneler ile çocukların tutumları arasındaki pozitif uyum (örneğin sıcaklıkta 0,26, korumada 0,55) diyabetli gruba göre hep daha yüksek kalmıştır. Yine de veri yapısı nedeniyle bazı katsayılar çok dalgalanmış ve bu modelden çıkan kesin sonuçlara ihtiyatla yaklaşılmıştır.': 'Madde-düzeyi ölçüm hatalarından arındırılmış diadik gizil yapılarda (CFA), kontrol grubunda daha yüksek ve tutarlı pozitif ilişki katsayıları izlenmiştir. Bununla birlikte tahmin zorlukları nedeniyle bulgu marjinaldir.',
        'İki kişinin gerçekte ne ölçüde aynı şeyden bahsettiğini ifade eden bu oranda; sıcaklıkta (0,19\'a karşı 0,02), aşırı korumada (0,36\'ya karşı 0,08) ve karşılaştırmada (0,20\'ye karşı 0,09) kontrol grubunun uyumu, diyabetli gruba kıyasla bariz şekilde daha yüksek bulunmuştur.': 'Aktör ve partner etkileri arasındaki orantısal dengeyi ifade eden k-katsayısı (anlam ortaklığı); sıcaklık (0,19\'a karşı 0,02), aşırı koruma (0,36\'ya karşı 0,08) ve karşılaştırma (0,20\'ye karşı 0,09) boyutlarında kontrol grubu lehine yüksek bulunmuştur.',
        'Baştaki kuralımız olan "bir tutumda uyum var demek için en az 3 strateji onaylamalıdır" şartı hiçbir grupta ve hiçbir durumda sağlanamamıştır. Yani anne-çocuk ikilisindeki ebeveynlik algısı uyumu genel olarak çok zayıftır. Daha da önemlisi; denenen 5 yöntemin tamamında (5/5) ve tüm alt boyutlarda, diyabetli anne-çocuk ikilisinin fikir ayrılığı kontrol grubuna göre çok daha belirgindir. Başka bir ifadeyle Tip 1 diyabet, ebeveynlik algısı konusunda anne ile çocuk arasındaki makası sağlıklı ailelere kıyasla daha da açmıştır.': 'Beş yöntemli karar kuralı, herhangi bir boyutta "yeterli diadik uyum" bulunduğu iddiasını reddetmiştir. Daha da kritik olarak, beş stratejinin beşi de diyabet grubundaki uyumsuzluğun kontrol grubuna göre daha derin olduğuna yakınsamıştır. Tip 1 diyabetin varlığı, aile içi ebeveynlik algı uyuşmazlığını yapısal olarak artırmaktadır.',
        
        # H5 figures and tables
        'H3 EMBU-P (annenin kendi bildirdiği ebeveynlik) değerlendirme tablosu: Annelerin dört ebeveynlik tutumunda diyabet ve kontrol grupları arası fark, önce yalın (birincil model) olarak, ardından ailelerin bazı özellikleri (sosyoekonomik vb.) istatistiksel olarak \'eşitlenip ağırlıklandırılarak\' (IPTW) verilmiştir. Tabloda etkinin boyutu (β), güven aralığı ve anlamlılık (p) sunulmuştur. Okuma anahtarı: Temel olarak güven aralığının sıfırı içerip içermediğine (sıfır varsa gruplar arası fark yoktur) bakılır; ağırlıklandırma (IPTW) yapıldığında da sonucun değişmediği görülür.': 'H3 anne öz-bildirimi (EMBU-P) grup farkı tablosu: Ham ANCOVA modeli ile IPTW ağırlıklandırılmış model bulguları. Standardize edilmemiş katsayı (b), sağlam (HC3) standart hata, %95 güven aralığı ve p-değerleri raporlanmıştır.',
        'H3 sağlamlık (duyarlılık) kontrolleri tablosu: Annelerin ebeveynlik farkı bulunmayışı bulgusu üç ayrı yolla yeniden sınanmıştır: antidepresan kullanım durumu, Bayesçi analiz ve eşdeğerlik sınaması (TOST). Okuma anahtarı: Bayes kanıtı (BF₁₀) değerinin 1\'in altında olması gruplar arası \'fark olmadığı\' yönündeki kanıtı destekler; TOST kararı ise belirlenen sınırlara göre grupların pratikte eşdeğer (aynı) kabul edilip edilemeyeceğini gösterir.': 'H3 sağlamlık (duyarlılık) analizleri: Yokluk/eşdeğerlik (null) bulgusunun antidepresan kullanımına göre yapılandırılmış (stratified) alt model, TOST pratik eşdeğerlik sınaması ve Bayesçi analiz (ROPE/BF) yöntemleriyle çapraz doğrulanmasını özetler.',
        'H3 antidepresan durumuna göre ayrıştırılmış orman grafiği: Annelerin bildirdiği dört ebeveynlik tutumunda gruplar (diyabet-kontrol) arası farkın antidepresan kullanıp kullanmamaya göre değişip değişmediğini gösterir. Noktalar tahmini etkiyi, yatay çizgiler ise güven aralığını ifade eder. Dikey kalın çizgi "sıfır fark" (fark yok) çizgisidir. Okuma anahtarı: Bir katmandaki yatay çizgi dikey sıfır çizgisine dokunuyor veya kesiyorsa, o durumda gruplar arasında anlamlı bir fark yoktur.': 'H3 antidepresan durumuna göre stratifiye orman grafiği: Aktif antidepresan kullanım durumuna göre ayrıştırılmış alt gruplarda (kullanan n=46; kullanmayan n=195) diyabet ve kontrol annelerinin ebeveynlik öz-bildirimlerindeki ortalama fark (b) ve %95 güven aralıkları.',
        'H4 Anne depresyonu ve ebeveynlik ilişkisi modeli: Annenin depresyon düzeyi (Beck) ile annenin ebeveynlik tutumları (EMBU-P) arasındaki yapısal ilişkilerin tablosudur. Tabloda etkinin gücü/yönü (β), güven aralığı ve anlamlılık (p) değerleri ile birlikte bu analiz modelinin genel uyum performansı sunulmuştur. Okuma anahtarı: β değerinin başında eksi (-) varsa o iki durumun zıt yönlü (biri artarken diğeri azalır), eksi yoksa aynı yönlü (ikisi birlikte artar) hareket ettiğini gösterir.': 'H4 Anne depresyonu (Beck) ve ebeveynlik (EMBU-P) yapısal eşitlik modeli (SEM): Gizil regresyon katsayıları (standartlaştırılmış β), standart hata (SE), %95 güven aralığı ve model uyum indekslerini içerir.',
        'H4 gruplar arası ölçüm adilliği tablosu: H4 modelinin, diyabetli annelerde ayrı kontrol grubu annelerinde ayrı mı davrandığı (taraflı ölçüm), yoksa her ikisinde de benzer kurallarla mı işlediği (adil cetvel) analiz edilmiştir. Üç farklı kısıtlama seviyesinde cetvelin gruplar arasında tutarlılığı test edilmiştir. Okuma anahtarı: İlgili Δ sütunlarının eksi veya artı değerlerde çok küçük (0,01 sınırında) kalması ölçüm cetvelinin gruplar arasında adil olduğuna (benzerliğe) işaret eder.': 'H4 ölçüm değişmezliği (measurement invariance) analizi: Yapısal eşitlik modelinin DM ve kontrol grupları arasındaki adilliğini (configural, metric ve scalar düzeylerde) test eden model karşılaştırması; ΔCFI ve ΔRMSEA eşikleri baz alınmıştır.',
        'H5 anne-çocuk uyumu (tutarlılık) tablosu: Annenin ebeveynlik anketi puanı ile çocuğun aynı ankete verdiği puan arasındaki uyum; sınıf-içi korelasyon, yüzey haritası, ortak yazgı, saf uyum ve Kenny anlam ortaklığı gibi her biri farklı bir açıya bakan 5 istatistiksel strateji ile özetlenmiştir. Okuma anahtarı: Her strateji grubun uyum veya uyumsuzluğuna dair yön belirtir (diyabet > kontrol veya kontrol > diyabet gibi). 5 stratejinin tamamına bakıldığında, kontrol grubundaki uyumun diyabete göre daha yüksek olduğu net biçimde görülür.': 'H5 diadik uyum karar tablosu: Beş istatistiksel stratejinin uyum büyüklüğü (katsayılar) ve diyabet/kontrol grubu uyum karşılaştırması özeti. Hiçbir strateji iki grup için de yeterli mutlak uyum eşiğini geçememiştir; tüm stratejiler kontrol grubunda nispi olarak daha yüksek tutarlılık bulgusuna yakınsamıştır.',
        'H5 Puan tutarlılığı haritası: Anne ile çocuğun aynı soruya verdiği puanların uyumu (Bland-Altman grafiği). Ortadaki kalın çizgi puan farkının sıfır olduğunu, noktalar ise ailelerin cevaplarını gösterir. Okuma anahtarı: Noktalar yatay sıfır çizgisi etrafında ne kadar dar (sıkı) bir alanda toplanıyorsa, anne ile çocuğun verdiği cevaplar o kadar aynıdır (uyumludur). Sınırların geniş olması aradaki fikir ayrılığının/uyumsuzluğun büyük olduğunu gösterir.': 'H5 Bland-Altman diadik uyum grafiği: Anne ve çocuk puanları arasındaki mutlak farkı (y-ekseni) dyad ortalamalarına (x-ekseni) göre çizer. Geniş güvenilirlik sınırları (LoA) zayıf mutlak tutarlılığa işaret eder.',
        'H5 uyumsuzluk (yanıt yüzeyi) 3D haritası: Annenin ebeveynlik puanı ile çocuğun puanı arasındaki uyumun/uyumsuzluğun annenin depresyonuyla (zemin yüksekliği) ilişkisini gösteren grafik. Sadece sıcaklık ve reddetme boyutları için çizilmiştir. Tabandaki kesik çizgi, anne ile çocuğun tam olarak aynı puanı verdiği "uyum hattı"dır. Okuma anahtarı: Sağdaki grafikte (diyabet reddetme), kesik çizgiye dik olan hatta (anne ve çocuğun fikirleri zıtlaştıkça) yüzeyin yukarı kıvrıldığı (depresyonun arttığı) görülmektedir. Bu tehlikeli zıtlaşma örüntüsü kontrol grubunda yoktur.': 'H5 Yanıt Yüzeyi Analizi (RSA) grafiği: Anne-çocuk ebeveynlik algısı uyum/uyumsuzluk eksenlerinin maternal depresyon düzeyine (z-ekseni) göre 3D topolojisi. Tabandaki köşegen tam uyum hattını temsil eder. Diyabetli grupta (sağ) reddetme algısındaki zıtlaşmanın yüksek depresyonla ilişkili olduğu yukarı kıvrımlı yüzeyden izlenebilir.'
    }

    count = 0
    for old, new in replacements.items():
        if old in content:
            content = content.replace(old, new)
            count += 1
            print(f"Replaced: {old[:30]}...")
        else:
            print(f"NOT FOUND: {old[:30]}...")

    with open("chapters/04_bulgular.qmd", "w", encoding="utf-8") as f:
        f.write(content)
    
    print(f"Total replaced in part 3: {count}")

process_file()
