import re

def process_file():
    with open("chapters/04_bulgular.qmd", "r", encoding="utf-8") as f:
        content = f.read()

    replacements = {
        'Kardeş ortalamaları üzerinden yürütülen aile düzeyi analizde, tüm boyutlarda gruplar arası fark etki büyüklüğü açısından önemsiz kalmıştır (d < 0,20).': 'Her evdeki iki kardeşin puan ortalamaları alınarak yürütülen aile düzeyi analizde, tüm boyutlarda gruplar arası fark etki büyüklüğü açısından klinik olarak önemsiz (d < 0,20) saptanmıştır.',
        'İkinci olarak, kardeşler arası diadik bağımlılığı denetleyen aktör-partner karşılıklı bağımlılık modeli (APIM) sonuçlarında da diyabet durumu veya hastalık rolü ana etkisi saptanmamıştır (p > 0,350).': 'Buna ek olarak, kardeşlerin ebeveynlik algılarında birbirlerini nasıl etkilediklerini (aktör ve partner etkileri) denetleyen yapısal modellerde de diyabet durumuna bağlı bir farklılık bulunamamıştır (p > 0,350).',
        'Latent düzeyde yürütülen Olsen-Kenny modeli çatışma boyutunda r = 0,27 düzeyinde anlamlı bir diadik uyum göstermiştir; bu bağımlılık yapısı cinsiyet kompozisyonu (aynı/farklı) ve kardeşler arası yaş farkından etkilenmemiştir.': 'Kavga/çatışma davranışlarının gizil (latent) düzeyde ayrıştırıldığı özel yapısal modellemelerde ise kardeşler arasında r = 0,27 düzeyinde anlamlı bir diadik uyum izlenmiş; bu ortak algı yapısının çocukların cinsiyetinden veya aralarındaki yaş farkından bağımsız olduğu görülmüştür.',
        'Bu boyutta ön-kayıtlı bir eşdeğerlik sınaması planlanmadığından, p-değeri temelli "farkın gösterilememesi" durumu nedensel bir "etki yokluğu" yerine istatistiksel belirsizlik olarak raporlanmıştır': 'Ön-kayıtlı bir eşdeğerlik sınaması planlanmadığından, p-değerine dayalı "fark bulunamaması" durumu doğrudan bir "etki yokluğu" yerine istatistiksel belirsizlik olarak raporlanmıştır',
        'H1 (çocuk algısı) bulgularındaki grup farklılıklarının anne öz-bildiriminde görülmemesi, değerlendiriciler arası uyuşmazlığa işaret etmekte olup tartışma bölümünde yapısal bir fenomen olarak ele alınmıştır.': 'Çocuk algısında saptanan grup farklılıklarının (H1) anne bildirimlerinde görülmemesi, değerlendiriciler arası algısal uyuşmazlığa işaret etmektedir.',
        'Çoklu karşılaştırma (BH-FDR) düzeltmeli birincil ANCOVA modelinde hiçbir alt ölçekte grup ana etkisi sıfırdan ayırt edilememiştir (p > 0,500).': 'Çoklu karşılaştırma düzeltmeli (BH-FDR) birincil kovaryans analizinde (ANCOVA), hiçbir ebeveynlik alt ölçeğinde gruplar arası anlamlı bir fark saptanmamıştır (p > 0,500).',
        'Gözlemsel karıştırıcıları denetleyen eğilim skoru ağırlıklandırması (IPTW) sonrasında da bulgu deseni değişmemiştir (p > 0,510). Annenin aktif antidepresan kullanımı bağlamında yapılandırılan alt grup duyarlılık analizinde de grup farkı yokluğu korunmuştur.': 'Karıştırıcı etkenleri denetleyen eğilim skoru ağırlıklandırması (IPTW) ve annenin aktif antidepresan kullanımını dışlayan duyarlılık analizlerinden sonra da "farksızlık" bulgusu korunmuştur.',
        'Buna ek olarak TOST istatistiksel eşdeğerlik sınaması, diyabet ve kontrol grubu annelerinin ebeveynlik puanlarının önceden tanımlanmış eşdeğerlik bandı (|SMD| < 0,30) içinde yer aldığını kanıtlamıştır': 'Ayrıca TOST eşdeğerlik sınaması, annelerin puanlarının uygulamada farksız sayılabilecek bir denklik bandı (|SMD| < 0,30) içinde yer aldığını kanıtlamıştır',
        'Anne depresif belirti yükü; azalan ebeveyn sıcaklığı, artan reddetme ve artan karşılaştırma tutumlarıyla istatistiksel olarak anlamlı biçimde ilişkilendirilmiştir. Bu yapısal bağlar enine kesitsel bir tasarımla elde edildiğinden nedensel bir yönelim değil, kovaryasyon örüntüsü yansıtır. Yapısal eşitlik modelinin uyum indekslerindeki kısıtlılıklar nedeniyle bulguların genellenebilirliği ihtiyatla değerlendirilmelidir.': 'Anne depresif belirti yükü; azalan şefkat (sıcaklık), artan reddetme ve artan karşılaştırma tutumlarıyla anlamlı düzeyde ilişkili bulunmuştur. Bu yapısal bağlar kesitsel bir tasarımla elde edildiğinden kesin bir neden-sonuç mekanizması olarak değil, eşzamanlı bir değişim örüntüsü olarak yorumlanmalıdır.',
        'Test edilen dört yapısal yoldan üçü anlamlı bulunmuştur: Yüksek depresif belirtiler düşük sıcaklık (β = −0,28), yüksek reddetme (β = 0,33) ve yüksek karşılaştırma (β = 0,28) ile öngörülmüştür (tümü için p < 0,001). Aşırı koruma boyutuyla depresyon arasındaki ilişki istatistiksel anlamlılığa ulaşmamıştır.': 'Depresyon ve ebeveynlik arasındaki dört yapısal yoldan üçü istatistiksel olarak anlamlı bulunmuştur: Depresif belirtiler arttıkça sıcaklık azalmış (β = −0,28), reddetme (β = 0,33) ve karşılaştırma (β = 0,28) boyutları ise artış göstermiştir (tümü p < 0,001). Aşırı koruma tutumu ile depresyon arasında ise belirgin bir bağ saptanamamıştır.',
        'RMSEA yeterli görünse de karşılaştırmalı uyum indeksleri (CFI, TLI) marjinal düzeyde kalmıştır. Ölçüm değişmezliği analizlerinde yapısal ağırlıklar modelinin diyabet ve kontrol grupları arasında kısmi değişmezlik sağladığı doğrulanmış, böylelikle raporlanan örüntünün her iki grup için de benzer yapıda işlediği teyit edilmiştir.': 'Modelin temel uyum indeksleri marjinal düzeyde kaldığından sonuçlara ihtiyatla yaklaşılmalıdır; bununla birlikte, diyabet ve kontrol aileleri arasında yapılan ölçüm değişmezliği analizleri, saptanan bu ilişki örüntüsünün her iki grupta da büyük ölçüde benzer çalıştığını doğrulamıştır.',
        'Bu diadik ayrışma; mutlak puan farkı, yanıt yüzeyi topolojisi ve gizil varyans ortaklığına odaklanan beş bağımsız stratejiyle analiz edilmiştir. Ön-kayıtlı karar kuralı uyarınca, gruplar arası uyum farkı iddiası için en az üç stratejinin yakınsaması (convergence) aranmıştır:': 'Bu uyumsuzluk; basit puan farklılıklarından öte, yanıt yüzeyi haritalaması ve ortak gizil faktör analizlerini içeren beş bağımsız istatistiksel stratejiyle çok yönlü olarak sınanmış ve bulguların çapraz tutarlılığı aranmıştır:',
        'Mutlak puan uyumunu test eden ICC değerleri tüm boyutta 0,10\'un altında kalarak zayıf tutarlılığa işaret etmiştir; DM grubunda katsayılar yer yer sıfırın altına (negatif değerlere) inmiştir. Dört boyutun tamamında kontrol grubundaki dyad tutarlılığı DM grubundan yüksektir': 'Sınıf-içi korelasyon katsayıları (ICC) tüm boyutlarda 0,10\'un altında kalarak zayıf bir uyuma işaret etmiş, diyabet grubunda bu katsayılar yer yer sıfırın altına inmiştir. Dört ebeveynlik boyutunun tamamında, sağlıklı kontrol ailelerindeki anne-çocuk uyumu diyabet grubundan daha yüksektir',
        'Bireysel puan sapmalarının yönünü üçüncü bir sonuç değişkeniyle (anne depresyonu) topolojik olarak ilişkilendiren yanıt yüzeyi analizinde; diyabetli ailelerde anne-çocuk reddetme uyuşmazlığı derinleştikçe anne depresif belirtilerinin doğrusal olmayan biçimde arttığı (b₁ ve a₄ parametreleri) saptanmıştır.': 'Anne ve çocuk arasındaki puan farklılıklarının annedeki depresyonla ilişkisini üç boyutlu bir yüzeyde haritalayan analizde; diyabetli grupta anne ile çocuğun reddetme algısı zıtlaştıkça anne depresyonunun belirgin biçimde arttığı gözlenmiştir.',
        'Dyad üyelerinin ortak bir gizil ebeveynlik faktörü etrafında kümelenme kapasitesi incelenmiştir. Sıcaklık dışındaki boyutlarda ortak faktör varyansı çözümlenemeyecek kadar düşük çıkmış; DM grubunda kontrol grubuna kıyasla daha düşük ortak faktör yükleri (non-convergence) gözlenmiştir.': 'Anne ve çocuğun ortak bir "aile tutumu" etrafında toplanıp toplanmadığı sınanmış, sıcaklık dışındaki boyutlarda ulaşılan bu ortak doku istatistiksel hata verecek düzeyde zayıf bulunmuştur. Diyabetli gruptaki yapısal kopukluk kontrol grubuna kıyasla daha belirgindir.',
        'Madde-düzeyi ölçüm hatalarından arındırılmış diadik gizil yapılarda (CFA), kontrol grubunda daha yüksek ve tutarlı pozitif ilişki katsayıları izlenmiştir. Bununla birlikte tahmin zorlukları nedeniyle bulgu marjinaldir.': 'Ölçüm hatalarından arındırılmış gizil yapılarda da (diadik CFA), kontrol grubundaki anneler ve çocukları arasındaki uyum katsayıları diyabetli gruba göre daha tutarlı ve yüksek izlenmiştir.',
        'Aktör ve partner etkileri arasındaki orantısal dengeyi ifade eden k-katsayısı (anlam ortaklığı); sıcaklık (0,19\'a karşı 0,02), aşırı koruma (0,36\'ya karşı 0,08) ve karşılaştırma (0,20\'ye karşı 0,09) boyutlarında kontrol grubu lehine yüksek bulunmuştur.': 'Anne ile çocuğun gerçekte ne ölçüde aynı kavramdan bahsettiğini değerlendiren yapısal oranda (Kenny k-katsayısı); sıcaklık, aşırı koruma ve karşılaştırma boyutlarında kontrol grubunun uyumu diyabetli gruba kıyasla bariz şekilde daha yüksek çıkmıştır.',
        'Beş yöntemli karar kuralı, herhangi bir boyutta "yeterli diadik uyum" bulunduğu iddiasını reddetmiştir. Daha da kritik olarak, beş stratejinin beşi de diyabet grubundaki uyumsuzluğun kontrol grubuna göre daha derin olduğuna yakınsamıştır. Tip 1 diyabetin varlığı, aile içi ebeveynlik algı uyuşmazlığını yapısal olarak artırmaktadır.': 'Uygulanan beş bağımsız stratejinin hiçbiri, anne ile çocuk arasında yeterli bir ebeveynlik algısı uyumu tespit edememiştir. Daha kritik olarak, test edilen tüm metrikler (5/5), diyabetli gruptaki anne-çocuk uyuşmazlığının kontrol grubuna kıyasla daha derin olduğunu doğrulamıştır. Bu durum, kronik hastalık yükünün aile içi algı farklılıklarını (makası) yapısal olarak artırdığına işaret etmektedir.',
        'Anne depresyonu ile çocuk algısı arasındaki ilişkide annenin reddedici tutumlarının olası aracı (mediator) rolü incelenmiştir': 'Annedeki depresif yükün çocuğun reddedilme hissine doğrudan mı, yoksa annenin reddedici davranışları üzerinden mi aktarıldığı istatistiksel olarak sınanmıştır',
        'Anne depresyonunun çocuk algısı üzerindeki etkisinin, annenin ebeveynlik öz-bildirimi üzerinden aracılık (mediation) gösterip göstermediği yapısal bir zincir modeliyle test edilmiş, ancak anlamlı bir dolaylı etki saptanmamıştır.': 'Anne depresyonu, anne tutumu ve çocuk algısı arasındaki köprü modeli üç katmanda test edilmiş, ancak istatistiksel olarak anlamlı bir aracı zincir kanıtlanamamıştır.',
        'Spesifik olarak, anne depresyonunun çocuk algısı üzerindeki etkisi maternal reddetme öz-bildirimi tarafından aracılık edilmemektedir.': 'Annenin depresyonunun çocuğun algısını etkilemesi, annenin kendi bildirdiği "reddedici ebeveynlik" tutumu üzerinden (dolaylı yoldan) gerçekleşmemektedir.',
        'Kesitsel tasarım sınırlılıkları çerçevesinde bu dolaysız ilişki nedensel bir etki değil, eşzamanlı bir kovaryasyon örüntüsü olarak değerlendirilmelidir.': 'Buna karşın, annenin depresyonu ile çocuğun "reddedildiğini" hissetmesi arasında dolaysız (doğrudan) ve pozitif bir bağlantı bulunmuştur. Bu veriler anlık bir tablo sunduğu için nedensel bir döngü değil, bir birlikte-değişim ilişkisi yansıtır.',
        'Çok düzeyli aile modellerinde ve diyabet durumuna göre kurgulanan koşullu süreç modellerinde de dolaylı etkinin bulunmadığı çapraz doğrulanmıştır.': 'Aile içi ilişkileri kontrol eden daha karmaşık (çok düzeyli) modellerde ve hastalık durumuna göre yapılan analizlerde de aracı etkinin yokluğu doğrulanmıştır.',
        'Aracılığın saptanamaması nedeniyle doğrudan etkilere (c\') odaklanıldığında, üç model spesifikasyonunun tümünde anne depresyonunun çocuktaki reddedilme algısını pozitif ve anlamlı düzeyde öngördüğü görülmüştür.': 'Zincirin tam olarak kurulamaması nedeniyle doğrudan etkilere odaklanılmış; her üç yöntemde de (3/3) anne depresyonunun, çocuğun reddedilme hissini istatistiksel olarak artırdığı tespit edilmiştir.',
        'Annelerin madde düzeyindeki yanıt örüntüleri temel alınarak, ebeveynlik tutumlarına göre gizil alt grupları belirleyen yapısal modeller (LCA/LPA) kurulmuştur.': 'Annelerin anket sorularına verdiği yanıtlardan yola çıkılarak, benzer tutum profili sergileyen aileleri gizil alt gruplara ayıran sınıflandırma modelleri kurulmuştur.',
        'Değişkenler arası çoklu koşullu bağımlılıkları, diğer tüm düğümler (nodes) kontrol edildikten sonra inceleyen istatistiksel ağ modelleri oluşturulmuştur.': 'Farklı aile içi duyguların (örneğin sıcaklık, çatışma, depresyon) birbiriyle olan doğrudan bağlarını, diğer tüm etkenlerden arındırılmış biçimde haritalayan ağ (network) çözümlemeleri uygulanmıştır.',
        'Ebeveynlik tutumu puanlarının annedeki olası depresif riski saptamadaki klinik geçerliliği ROC analizi ve karar eğrisi (DCA) ile değerlendirilmiştir': 'Yalnız ebeveynlik tutumları kullanılarak annedeki potansiyel depresyon riskinin tespit edilip edilemeyeceği, poliklinik pratiği göz önünde bulundurularak ROC ve Karar Eğrisi (DCA) algoritmalarıyla sınanmıştır',
        'HbA1c verisi mevcut olan dar bir alt örneklemde (n = 39) betimsel olarak incelenmiştir.': 'Hastalık süresi veya HbA1c seviyesi gibi sadece hasta grubunda tanımlı parametrelerin aile algısı üzerindeki etkileri, veri eksiği bulunmayan dar bir alt örneklemde (n = 39) betimsel olarak incelenmiştir.'
    }

    count = 0
    for old, new in replacements.items():
        if old in content:
            content = content.replace(old, new)
            count += 1
            print(f"Replaced: {old[:30]}...")
        else:
            print(f"NOT FOUND: {old[:30]}...")

    with open("chapters/04_bulgular.qmd", "w", encoding="utf-8") as f:
        f.write(content)
    
    print(f"Total replaced in ch4 late: {count}")

process_file()
