import sys

file_path = "chapters/04_bulgular.qmd"

with open(file_path, "r", encoding="utf-8") as f:
    content = f.read()

replacements = {
    """#| tbl-cap: "Aracılık ve koşullu süreç çözümlemesi sonuçları: anne depresyonu (Beck) → algılanan anne reddetmesi (EMBU-P) → çocuğun algıladığı reddetme (EMBU-C) zinciri. Sütunlar a-yolu ve b-yolu katsayılarını, bunların çarpımı olan dolaylı etkiyi (BCa bootstrap, n = 1000), doğrudan etkiyi (c'), koşullu süreçte (Hayes Model 14) grup moderasyonunu ve aracılı moderasyon indeksini (IMM) verir. Okuma anahtarı: dolaylı etkinin %95 güven aralığı sıfırı içeriyorsa o zincirde aracılık gösterilmemiş sayılır; a-yolunun tek başına anlamlı olması aracılık kanıtı değildir." """:
    """#| tbl-cap: "Aracılık analiz sonuçları: 'Anne depresyonu → annenin reddetme tutumu → çocuğun reddedildiğini hissetmesi' şeklinde bir zincirleme etki olup olmadığını test eder. Okuma anahtarı: 'Dolaylı etki' sütunundaki güven aralığı sıfırı içeriyorsa, bu zincirleme bağlantının çalışmadığına, yani ilişkinin annenin bildiriminden 'aracı olarak' geçmediğine hükmedilir." """,

    """#| tbl-cap: "Latent profil analizi (LPA), latent sınıf analizi (LCA) ve Bifaktör S-1 modeli için model-seçim tanıları: anne depresyonu (Beck), dört EMBU-P alt ölçeği ve latent sosyoekonomik düzey göstergeleri üzerinde profil/sınıf sayısına göre. Sütunlar her aday çözüm için BIC, entropi ve bootstrap olabilirlik oran testi (BLRT) p değerini verir. Okuma anahtarı: en düşük BIC tek başına seçim ölçütü değildir; parsimoni kuralı (ΔBIC ≤ 2) ve entropi (0,80 üzeri iyi ayrım) birlikte değerlendirilir." """:
    """#| tbl-cap: "Aileleri gruplara (profillere) ayırma analizi (LPA/LCA): Tüm ailelerin psikolojik ve sosyoekonomik verilerine bakılarak veri setinin içinde kendiliğinden doğal gruplar/profiller olup olmadığını arar. Tablo, bu profillerin 1'den 5'e kadar sınıflandırılmasının ne kadar mantıklı/uyumlu (BIC/Entropi) olduğunu gösterir. Okuma anahtarı: Entropinin 0,80'e yakın ve BIC'in düşük olması, ayrılan grupların birbirine karışmayan temiz profiller olduğunu gösterir." """,

    """![[KEŞİFSEL] Latent profil analizi model-seçim tanıları: BIC, entropi ve bootstrap olabilirlik oran testi (BLRT) p değeri profil sayısına göre çizilmiştir. BIC sayısal minimumu 4-profildedir; bununla birlikte, ΔBIC≈2 parsimoni eşiği ve yorumlanabilirlik gerekçesiyle 3 ile 4 profil arası model-seçim belirsizliği altında keşifsel sunum için 3-profil çözümü benimsenmiştir. Okuma anahtarı: en düşük BIC tek başına seçim değildir; profil sayısı BIC eğrisi, entropi ve BLRT birlikte okunarak parsimoni kuralına göre belirlenir.](docs/assets/figures/carbon/primary/fig-15-lpa-fit-indices.svg){#fig-lpa-fit-indices width="78%" fig-align="center"}""":
    """![Aile profilleri ayırma analiz grafikleri: İstatistiksel programın veride kaç farklı 'tip/profil' aile bulduğunu ve bu ayrımların (3, 4 veya 5 grup) ne kadar isabetli olduğunu gösterir. Okuma anahtarı: Düşük BIC çizgisi ve yüksek Entropi uyumu arzu edilir. Veriler, araştırılan grupta en isabetli seçeneğin aileleri 3 farklı temel profile ayırmak olduğunu göstermiştir.](docs/assets/figures/carbon/primary/fig-15-lpa-fit-indices.svg){#fig-lpa-fit-indices width="78%" fig-align="center"}""",

    """#| tbl-cap: "Ağ merkeziyet ölçütleri ve Ağ Karşılaştırma Testi (NCT) sonuçları: dört EMBU-P alt ölçeği, dört kardeş ilişkisi (SRQ) alt ölçeği ve anne depresyonu (Beck) toplam puanı olmak üzere dokuz gösterge üzerinde kurulan EBIC-LASSO Gauss grafik modeli (γ = 0,5; havuzlanmış n = 238). Sütunlar en güçlü kenarları, düğüm strength merkeziyetini, case-dropping bootstrap kararlılık katsayısını ve DM ile kontrol ağlarını karşılaştıran NCT (ağ invaryansı, global strength) p değerlerini verir. Okuma anahtarı: kenar bir kısmi korelasyondur (koşullu bağımlılık), nedensel ok değildir; NCT'de anlamlı fark bulunmaması iki ağın özdeş olduğu anlamına gelmez." """:
    """#| tbl-cap: "Aile içi ilişkilerin istatistiksel ağ (network) analizi sonuçları: Annelerin tutumları, kardeşlerin ilişkileri ve depresyon gibi 9 temel konunun birbiriyle nasıl bir 'örümcek ağı' gibi bağlandığını özetler. Okuma anahtarı: Hangi özelliğin ağın tam 'merkezinde' yer aldığını (en çok etkileşen/bağlanan konu) gösterir. Karşılaştırma testi (NCT), bu ilişki ağının diyabetli aileler ile sağlıklı ailelerde genel olarak benzer olduğunu göstermektedir." """,

    """![[KEŞİFSEL] EBIC-LASSO Gauss grafik modeli (ağ diyagramı): dokuz gösterge (dört EMBU-P + dört kardeş ilişkisi/SRQ alt ölçeği + anne depresyonu/Beck toplam puanı; γ = 0,5; havuzlanmış n = 238) arasındaki doğrudan bağlantı iskeleti. Kenar kalınlığı mutlak kısmi korelasyonu (diğer tüm göstergeler sabitken kalan ilişkiyi), düğüm boyutu strength merkeziyetini gösterir. Okuma anahtarı: en kalın kenarlarla bağlı ve en büyük düğümler en merkezî göstergelerdir; kenar yokluğu koşullu bağımsızlık iddiasıdır ve hiçbir kenar nedensel ok olarak okunmaz.](docs/assets/figures/carbon/primary/fig-16-network-graph.svg){#fig-network-graph width="82%" fig-align="center"}""":
    """![Aile içi ilişkilerin ağ (network) haritası: Ebeveynlik, kardeş ilişkisi ve depresyonun birbirine nasıl bağlandığını gösteren görseldir. Okuma anahtarı: Çizgilerin (kenarların) kalınlığı o iki konu arasındaki bağın ne kadar güçlü ve doğrudan olduğunu gösterir. Dairelerin (düğümlerin) büyüklüğü ise o konunun ailenin dinamiğinde ne kadar kilit (merkezî) bir rolde oturduğunu ifade eder.](docs/assets/figures/carbon/primary/fig-16-network-graph.svg){#fig-network-graph width="82%" fig-align="center"}""",

    """![[KEŞİFSEL] Ağ Karşılaştırma Testi (NCT) sonuçları: DM ve kontrol ailelerinin dokuz-göstergeli ebeveynlik/kardeş/depresyon ağları iki eksende karşılaştırılır — ağ invaryansı (bağlantı yapısı) ve global strength (toplam bağlantı gücü). Grafik her eksen için permütasyon temelli test istatistiğini ve p değerini gösterir. Okuma anahtarı: p değeri eşik altındaysa iki ağ o eksende ayrışır; anlamlı fark bulunmaması ağların özdeş olduğunun kanıtı değil, mevcut örneklemde farkın gösterilemediğidir.](docs/assets/figures/carbon/primary/fig-17-network-nct.svg){#fig-network-nct width="72%" fig-align="center"}""":
    """![Diyabetli ve kontrol ağlarının karşılaştırma testi (NCT): Diyabetli ailelerin ilişkilerindeki bağ yapısı ile kontrol ailelerinin bağ yapısı arasında genel bir fark olup olmadığını kontrol eden görseldir. Okuma anahtarı: 'p değeri' belirlenen kuralın altındaysa fark var demektir. Tablodaki veriler, genel yapının (örümcek ağının biçiminin) iki grup arasında benzer olduğunu göstermiştir.](docs/assets/figures/carbon/primary/fig-17-network-nct.svg){#fig-network-nct width="72%" fig-align="center"}""",

    """#| tbl-cap: "Yüksek anne depresif belirti düzeyini eşzamanlı sınıflandıran tarama modelinin performansı: temel model (DM grup + anne yaşı + latent sosyoekonomik düzey + aile çocuk sayısı) ile genişletilmiş model (temel + dört EMBU-P alt ölçeği), iç-validasyonlu optimizm-düzeltilmiş bootstrap (B = 1000) ile. Sütunlar ayrım gücünü (AUC), Youden işletme noktasında duyarlılık, özgüllük, pozitif ve negatif kestirim değerlerini (PPV, NPV) ve kalibrasyon eğim/sabitini verir. Okuma anahtarı: AUC 0,5 şans düzeyidir, 0,70–0,80 kabul edilebilir ayrım bandıdır; bu bir kesitsel eşzamanlı sınıflandırmadır, ileriye dönük risk yordaması değildir." """:
    """#| tbl-cap: "Anne depresyonu tarama modeli performansı: Annelerin depresyon riskini temel bilgilerle (yaş, çocuk sayısı, vb.) ve ebeveynlik tutumlarıyla (geniş model) ne kadar doğru sınıflandırabildiğimizi gösterir. Okuma anahtarı: AUC (eğri altı alan) modelin ayırma gücünü gösterir; 0,5 rastgele atış yapmakla eşdeğerken, 0,70-0,80 arası kabul edilebilir, iyi bir başarıyı temsil eder." """,

    """![[KEŞİFSEL] Yüksek anne depresif belirti (Beck) düzeyinin eşzamanlı sınıflandırması için ROC eğrisi: temel model demografi/sosyoekonomik düzey (SES) değişkenlerini, geniş model buna ek dört EMBU-P alt ölçeğini içerir; iç-validasyonlu optimizm-düzeltilmiş bootstrap ile. Her eğri, tüm karar eşiklerinde gerçek-pozitif oranı ile yanlış-pozitif oranı arasındaki dengeyi çizer; köşegen şans düzeyidir. Okuma anahtarı: eğri sol-üst köşeye ne kadar yakınsa ayrım o kadar güçlüdür (eğri altı alan AUC); bu kesitsel eşzamanlı sınıflandırmadır, ileriye dönük risk yordaması değildir.](docs/assets/figures/carbon/primary/fig-18-clinical-roc.svg){#fig-clinical-roc width="78%" fig-align="center"}""":
    """![Anne depresyonu için sınıflandırma (ROC) eğrisi: Temel bilgilerin (yaş vb.) ve annenin ebeveynlik tutumlarının, depresyonu ne kadar doğru tespit edebildiğini (ayırma gücünü) gösteren grafiktir. Kesikli çapraz çizgi tamamen şans eseri (yazı-tura gibi) tahmini temsil eder. Okuma anahtarı: Renkli eğriler sol üst köşeye ne kadar yakın şişiyorsa, modelin doğru bilme (depresyonlu ile depresyonsuzu ayırt etme) yeteneği o kadar yüksektir.](docs/assets/figures/carbon/primary/fig-18-clinical-roc.svg){#fig-clinical-roc width="78%" fig-align="center"}""",

    """![[KEŞİFSEL] Klinik karar eğrisi analizi (DCA): geniş eşzamanlı sınıflandırma skoru, herkesi tara ve kimseyi tarama kıyas stratejileriyle eşik olasılığına göre net fayda düzeyinde karşılaştırılır. Net fayda değerleri görünür (apparent, optimizm-düzeltilmemiş) iç-örneklem değerleridir. Okuma anahtarı: model eğrisi iki kıyas çizgisinin üstünde kaldığı eşik aralığında klinik değer taşır; net fayda doğruluğu değil, o skorla karar vermenin fayda-zarar dengeli net kazancını ölçer.](docs/assets/figures/carbon/primary/fig-19-clinical-dca.svg){#fig-clinical-dca width="86%" fig-align="center"}""":
    """![Klinik karar (fayda/zarar) eğrisi: Bu modeli kullanarak anneleri depresyon açısından taramanın, 'herkesi tara' veya 'hiç kimseyi tarama' gibi körleme stratejilere göre ne kadar net fayda (pratik kazanç) sağlayacağını gösterir. Okuma anahtarı: Model eğrisinin diğer iki basit (körleme) çizginin üzerinde kaldığı her nokta, modelin kullanılmasının doktorlara ve hastalara zaman/emek açısından fayda sağladığı (gereksiz işlem yaptırmadığı) anlamına gelir.](docs/assets/figures/carbon/primary/fig-19-clinical-dca.svg){#fig-clinical-dca width="86%" fig-align="center"}""",

    """![[KEŞİFSEL] Geniş eşzamanlı sınıflandırma skorunun görünür (apparent) kalibrasyon grafiği: her nokta bir olasılık bini için tahmin edilen olasılık ile gözlenen oranı eşler; kesikli köşegen kusursuz kalibrasyonu gösterir. Grafikteki bin'ler görünür (optimizm-düzeltilmemiş) tahminlerden üretilmiştir; optimizm-düzeltilmiş eğim/sabit ve %95 güven aralıkları @tbl-apa-clinical içinde raporlanır. Okuma anahtarı: noktalar köşegen üzerinde toplanıyorsa tahminler gözlemle uyumludur, köşegenden sistematik sapma tahminlerin sistematik yüksek/düşük kaydığını yansıtır.](docs/assets/figures/carbon/primary/fig-20-clinical-calibration.svg){#fig-clinical-calibration width="78%" fig-align="center"}""":
    """![Tahmin doğruluk (kalibrasyon) grafiği: Modelin verdiği '%X risk' tahmini ile gerçek hayattaki oranların ne kadar örtüştüğünü gösterir. Okuma anahtarı: Kesikli köşegen çizgi 'kusursuz tahmini' temsil eder. Noktalar bu çapraz çizgi üzerinde toplanmışsa, modelin tahminleri güvenilir demektir; çizgiden uzaklaşma ise modelin olayları olduğundan daha fazla veya az riskli gördüğüne (yanıldığına) işaret eder.](docs/assets/figures/carbon/primary/fig-20-clinical-calibration.svg){#fig-clinical-calibration width="78%" fig-align="center"}""",

    """![[KEŞİFSEL] Klinik model tamamlayıcıları: doğrusal olmayan iki yöntemle sınıflandırma — bir karar ağacının (CART) çapraz-doğrulanmış hata profili ve onun topluluk hâli olan Random Forest'ın değişken önem sıralaması birlikte gösterilir. Bir panel ağaç karmaşıklığına göre çapraz-doğrulanmış hatayı, diğer panel her göstergenin sınıflandırmaya göreli katkısını verir. Okuma anahtarı: CART hatasının en düşük olduğu karmaşıklık düzeyi budama noktasını işaret eder; Random Forest değişken önemi sınıflandırmaya katkıyı gösterir, nedensel önem sıralaması değildir.](docs/assets/figures/carbon/primary/fig-21-clinical-cart-rf.svg){#fig-clinical-cart-rf width="82%" fig-align="center"}""":
    """![Alternatif tahmin modelleri ve değişken önem sıralaması (Yapay Öğrenme Algoritmaları): Anne depresyonunu tahmin ederken hangi bilgilerin (soruların/özelliklerin) daha belirleyici olduğunu makine öğrenimi yöntemleriyle gösterir. Okuma anahtarı: Sağdaki grafikte (Random Forest), çubukların uzunluğu o özelliğin doğru tahmine yaptığı genel katkıyı (önemi) ifade eder. Bu bir neden-sonuç değil, ipucu sırasıdır.](docs/assets/figures/carbon/primary/fig-21-clinical-cart-rf.svg){#fig-clinical-cart-rf width="82%" fig-align="center"}"""
}

for old, new in replacements.items():
    content = content.replace(old, new)

with open(file_path, "w", encoding="utf-8") as f:
    f.write(content)

print("Part 3 replacements done.")
