import sys

file_path = "chapters/04_bulgular.qmd"

with open(file_path, "r", encoding="utf-8") as f:
    content = f.read()

replacements = {
    """#| tbl-cap: "Örneklem özellikleri tablosu: DM ve kontrol aileleri, aile düzeyi sosyodemografik, anne ruh sağlığı, klinik ve psikolojik göstergeler bakımından yan yana betimlenir. Satırlar değişken ailesine göre gruplanmıştır; hücreler ort. (SS), medyan [ÇAA] veya n (%) biçimindedir ve her satırda iki grubun ayrışma derecesi standardize ortalama farkla (SMD) verilir. Okuma anahtarı: SMD sütunu bir denge geleneğine göre taranır — |SMD| < 0,10 iyi denge, 0,10–0,25 sınırda, 0,25–0,50 dengesiz, ≥ 0,50 ciddi dengesizlik bandına karşılık gelir; bu değer istatistiksel bir anlamlılık ölçüsü değil, gruplar arası ayrışmanın ölçeksiz büyüklüğüdür." """:
    """#| tbl-cap: "Örneklem özellikleri tablosu: Diyabetli ve sağlıklı (kontrol) aileler; sosyodemografik durumları, anne ruh sağlığı ve psikolojik durumları açısından yan yana karşılaştırılmaktadır. Tabloda her bir özelliğin iki gruptaki ortalamaları ve yüzdeleri verilmiştir. Okuma anahtarı: Sağdaki SMD (fark) sütunu, iki grubun birbirine ne kadar benzediğini gösterir. Bu değerin 0,10'dan küçük olması iki grubun çok benzer (dengeli) olduğunu, 0,50'den büyük olması ise aralarında ciddi bir fark bulunduğunu ifade eder." """,

    """#| tbl-cap: "Kovaryat dengesi tablosu (Love grafiğinin sayısal karşılığı): birincil ayarlama setindeki her değişken için gruplar arası fark, ağırlık öncesi, stabilize ters-olasılık ağırlıklandırması (IPTW) sonrası ve eşleştirme sonrası mutlak standardize ortalama fark (|SMD|) değeri ile IPTW kararı sütunlar hâlinde verilir. Ayarlama seti latent SES, kardeş yaş farkı ve aile çocuk sayısından oluşur. Okuma anahtarı: her değişkende ağırlık öncesi ve sonrası |SMD| sütunları karşılaştırılır — değerin 0,10 eşiğinin altına inmesi o değişkende dengelenmeye karşılık gelir; tablo yalnız ayarlama setinin dengesini belgeler, tüm ham değişkenlerin değil." """:
    """#| tbl-cap: "Dengeleme tablosu: Araştırmada adil bir karşılaştırma yapmak için bazı özelliklerin (sosyoekonomik durum, çocuk sayısı vb.) matematiksel olarak 'eşitlenmesi' (ağırlıklandırılması) gerekmiştir. Bu tablo eşitleme işleminden önce ve sonra gruplar arasındaki farkı gösterir. Okuma anahtarı: İşlem sonrasındaki fark (|SMD|) sütununda değerin 0,10'un altına inmesi, o özelliğin iki grupta artık başarıyla dengelendiği (eşitlendiği) anlamına gelir." """,

    """#| tbl-cap: "Eksik veri özeti tablosu: her değişken için analitik payda, analitik eksik n ve yüzdesi ile çalışma tasarımından kaynaklanan yapısal boş hücre sayısı ve ele alma stratejisi ayrı ayrı listelenir. Okuma anahtarı: her satırda eksikliğin analitik mi (gerçekten toplanamayan) yoksa tasarım kaynaklı mı (yalnız DM çocuklarında ölçülen HbA1c/DM süresi gibi tanım gereği gözlenmeyen) olduğu ayırt edilir; bu ayrım tablonun kalbidir ve tasarım kaynaklı boşluklar, analitik eksiklikten farklı olarak imputasyonla doldurulmaz." """:
    """#| tbl-cap: "Eksik veri özeti tablosu: Hangi verilerin tam olarak toplanamadığı (eksik kaldığı) listelenmiştir. Okuma anahtarı: Tabloda iki tür boşluk ayrılmıştır: Biri ulaşılamayan 'gerçek eksik' veriler, diğeri ise araştırmanın doğası gereği sorulmayan 'yapısal' boşluklardır (örneğin sağlıklı çocuklara diyabet süresi sorulmaması gibi)." """,

    """#| tbl-cap: "Eğilim skoru modeli ve ortak destek tablosu: üst kısımda grup üyeliğini yordayan lojistik regresyonun katsayıları odds oranı (OR) ve %95 güven aralığı (GA) biriminde, alt kısımda stabilize IPTW ağırlık ile ortak destek özeti verilir. Model girdileri nedensel diyagramdan gelir (latent SES, kardeş yaş farkı, aile çocuk sayısı). Okuma anahtarı: üst kısımda her yordayıcının OR'una ve %95 GA'sının 1'i içerip içermediğine bakılır (GA 1'i içeriyorsa yordayıcı sinyali belirsizdir), alt kısımda ortak desteğin çakışma aralığı okunur; ortak destek karşılaştırılabilirliğin ön koşuludur, dengenin kendisi değildir." """:
    """#| tbl-cap: "Dengeleme (eğilim skoru) tablosu: Ailelerin hangi özelliklerine bakılarak gruplara ayrıldığı ve matematiksel eşitlemenin (ağırlıklandırmanın) arka plan hesaplamaları verilmiştir. Okuma anahtarı: Tablonun alt kısmında grupların birbirleriyle ne kadar ortak noktası olduğu (ortak destek aralığı) özetlenmiştir. Ortak noktanın bulunması, adil bir karşılaştırma yapabilmenin ilk şartıdır." """,

    """#| tbl-cap: "SES kompozit bileşenleri ve latent SES doğrulayıcı faktör analizi (CFA) uyum ölçütleri tablosu: eğitim, mesleki statü ve materyal göstergelerinin tek bir latent SES ölçüsünde birleştirilmesi ve bu birleştirmenin uyumu belgelenir. Okuma anahtarı: bileşenlerin latent SES'e yükleme yapısı (kompozit geçerliği) ile CFA uyum ölçütlerinin kabul bandında olup olmadığı incelenir. Birden büyük TLI değerleri örneklem oynamasından kaynaklanır ve iyi uyuma işaret eder; bazı yazılımlar raporlamada 1,00'a sınırlar." """:
    """#| tbl-cap: "Sosyoekonomik durum (SES) bileşenleri tablosu: Ailelerin eğitim, meslek ve maddi durum verilerinin tek bir birleşik sosyoekonomik puanda nasıl harmanlandığı gösterilmiştir. Okuma anahtarı: Alt kısımdaki uyum ölçütleri, farklı verilerin tek bir puan oluşturmak için ne kadar başarılı ve mantıklı şekilde birleştiğini kanıtlar." """,

    """![Analitik örneklem akış diyagramı: kilitlenmiş kanonik veri tabanından aile düzeyi analiz tabanına, DM ve kontrol gruplarına ve yalnız DM grubundaki klinik alt-analiz katmanına uzanan eleme zinciri kademe kademe gösterilir. Çekirdek örneklem 241 aileden (120 DM + 121 kontrol) ve 482 çocuk satırından (241 × 2; her aileden bir indeks çocuk ve bir kardeş) oluşur. Okuma anahtarı: kutulardan aşağı inilerek her adımda hangi kademeye kaç birimin taşındığı izlenir; tarama öncesi (davet edilen/reddeden aile) akışı kanonik kilitte izlenemediğinden diyagram yalnız doğrulanabilir analiz-seti akışını gösterir — bir katılım oranı ya da temsiliyet kanıtı değildir.](docs/assets/figures/carbon/primary/fig-01-strobe-flow.svg){#fig-strobe-flow width="82%" fig-align="center"}""":
    """![Örneklem akış diyagramı: Araştırmaya katılan ailelerin başlangıçtan son analiz aşamasına kadar nasıl şekillendiği adım adım gösterilmektedir. Temel veri seti 241 aile ve onlardan gelen 482 çocuktan oluşur. Okuma anahtarı: Kutulardan aşağı inildikçe, verilerin nasıl gruplandığı (diyabetli/kontrol) izlenebilir. Araştırma öncesi daveti reddedenlerin kesin sayısı veri setinde yer almadığı için bu şema genel bir 'katılım oranı' değil, sadece elde mevcut verinin haritasıdır.](docs/assets/figures/carbon/primary/fig-01-strobe-flow.svg){#fig-strobe-flow width="82%" fig-align="center"}""",

    """![Nedensel yönlü asiklik graf (DAG) ve kovaryat ayarlama stratejisi: her düğüm bir değişkeni, her ok bir 'şu şunu etkiler' varsayımını temsil eder (oklar veriden kestirilmez, analizden önce çizilir; bir okun yokluğu da bir varsayımdır). Düğümler üç işleve ayrılır — karıştırıcılar (latent SES, kardeş yaş farkı, aile çocuk sayısı; hem T1DM'ye hem çocuk algısı/kardeş ilişkisi çıktısına ok gönderir ve birincil modelde ayarlanır), aracı/duyarlılık düğümleri (Beck ve antidepresan kullanımı; bilerek açık bırakılır) ve seçilim düğümü S (merkez, takvim dönemi ve grup üyeliği birlikte kimin örnekleme girdiğini belirler; analiz S=1 örneklemine koşulludur ve şekilde kesikli gösterilir). Okuma anahtarı: hangi düğümün karıştırıcı (kapatılacak), hangisinin aracı (açık bırakılacak) ve hangisinin seçilim düğümü olduğu izlenir; seçilim düğümü S üzerinde koşullanma nedeniyle T1DM'nin toplam nedensel etkisi bu tasarımda tanımlanamaz, dolayısıyla grup katsayıları nedensel etki olarak değil, gözlenen karıştırıcılar için ayarlanmış koşullu ilişki olarak okunur.](docs/assets/figures/carbon/primary/fig-02-causal-dag.svg){#fig-causal-dag width="94%" fig-align="center"}""":
    """![Nedensel yol haritası (DAG): Hangi faktörün hangisini etkileyebileceğini gösteren mantıksal bir plandır. Düğümler özellikleri, oklar ise etkinin yönünü gösterir. Okuma anahtarı: İşaretli oklar araştırılan asıl konuyu, diğer çizgiler ise hesaplamalarda arka planda 'kontrol edilmesi' (eşitlenmesi) gereken diğer faktörleri (çocuk sayısı, gelir durumu vb.) gösterir. Bu harita, verilerin analizine matematiksel bir rehberlik eder.](docs/assets/figures/carbon/primary/fig-02-causal-dag.svg){#fig-causal-dag width="94%" fig-align="center"}""",

    """![Kovaryat denge kazanımı grafiği (Love grafiği): birincil ayarlama setindeki her değişken için gruplar arası mutlak standardize ortalama fark (|SMD|), ağırlık öncesi, IPTW sonrası ve eşleştirme sonrası aşamalar renkle ayrılarak çizilir. Satırlar ayarlama seti değişkenleridir (latent SES, kardeş yaş farkı, aile çocuk sayısı); yatay eksen |SMD| büyüklüğüdür. Okuma anahtarı: her kovaryatta noktaların ağırlıklandırmadan sonra sıfıra yaklaşıp yaklaşmadığına, yani öncesi/sonrası kıyasına bakılır; kesikli çizgiler 0,10 ve 0,25 denge eşiklerini gösterir ve sıfıra yakınlık grup dengesine karşılık gelir. Grafik yalnız ayarlama setinin dengesini gösterir, tüm ham değişkenlerin değil.](docs/assets/figures/carbon/primary/fig-03-smd-love-plot.svg){#fig-smd-love width="84%" fig-align="center"}""":
    """![Denge kazanımı (Love) grafiği: Sosyoekonomik durum veya kardeş yaş farkı gibi özelliklerin iki grupta ne kadar eşitlendiğini gösteren görseldir. Okuma anahtarı: Yatay eksendeki sıfır çizgisi tam eşitliği ifade eder. Noktaların işlem (ağırlıklandırma) sonrasında sıfır çizgisine doğru yaklaşması, gruplar arasındaki farkın kapatıldığını ve karşılaştırmanın adil hâle getirildiğini gösterir.](docs/assets/figures/carbon/primary/fig-03-smd-love-plot.svg){#fig-smd-love width="84%" fig-align="center"}""",

    """![Eğilim skoru ortak destek dağılımı: DM ailelerinin ve kontrol ailelerinin eğilim skoru yoğunluk dağılımları üst üste çizilir ve çakışan alan (ortak destek) gösterilir. Eğilim skoru, bir ailenin arka plan özelliklerine (latent SES, kardeş yaş farkı, aile çocuk sayısı) bakılarak DM grubunda olma olasılığıdır. Okuma anahtarı: iki dağılımın çakışıp çakışmadığına ve çakışan bölgenin ne kadar geniş olduğuna bakılır; örtüşme grupların karşılaştırılabilir olup olmadığını (ön koşulu) gösterir, dengenin kendisini değil (dengeyi Love grafiği belgeler).](docs/assets/figures/carbon/primary/fig-04-propensity-overlap.svg){#fig-propensity-overlap width="84%" fig-align="center"}""":
    """![Grupların örtüşme (ortak destek) grafiği: Diyabetli ve kontrol ailelerinin özellikleri bakımından birbirine ne kadar benzediği, eğrilerin kesişimiyle görselleştirilmiştir. Okuma anahtarı: İki renkli eğrinin üst üste bindiği (kesiştiği) alanın genişliği, bu iki grubun güvenilir bir şekilde birbiriyle kıyaslanabileceğini gösterir.](docs/assets/figures/carbon/primary/fig-04-propensity-overlap.svg){#fig-propensity-overlap width="84%" fig-align="center"}""",

    """![Latent SES kompozit bileşen korelasyon matrisi (ısı haritası): latent SES göstergesinin eğitim, mesleki statü (ISEI-08) ve materyal bileşenlerle korelasyon yapısı hücre hücre çizilir; her hücrenin rengi korelasyonun büyüklüğünü ve işaretini kodlar. Okuma anahtarı: kompozit satır/sütununda en koyu ve aynı yönlü hücreler aranır — bileşenlerin kompozitle güçlü ve pozitif korelasyonu iç tutarlılığı destekler; renk yoğunluğu ilişkinin büyüklüğünü gösterir, istatistiksel anlamlılığını değil.](docs/assets/figures/carbon/primary/fig-05-ses-correlation-heatmap.png){#fig-ses-correlation width="74%" fig-align="center"}""":
    """![Sosyoekonomik göstergelerin ısı haritası: Ailenin geliri, anne-babanın mesleği ve eğitim durumu gibi farklı verilerin birbiriyle ne kadar uyumlu olduğunu renklerle gösterir. Okuma anahtarı: Renklerin koyuluğu, o iki özelliğin birbiriyle ne kadar güçlü bir ilişki (korelasyon) içinde olduğunu ifade eder.](docs/assets/figures/carbon/primary/fig-05-ses-correlation-heatmap.png){#fig-ses-correlation width="74%" fig-align="center"}""",

    """![Birincil analiz değişkenlerinde analitik eksik veri örüntüsü haritası: yalnız gerçekten toplanamayan (analitik) eksiklik, FIML/çoklu atama çerçevesine giren değişken düzeyinde çizilir (toplam ≈ %0,3). Okuma anahtarı: hangi değişkende ne oranda boşluk olduğu ve boşlukların nerede kümelendiği izlenir; tasarım kaynaklı yapısal eksik hücreler (kontrol grubunda DM yılı ve HbA1c) bu görselde yer almaz, çünkü bunlar analitik eksiklik değil, tanım gereği gözlenmeyen hücrelerdir.](docs/assets/figures/carbon/primary/fig-06-missing-pattern-primary.png){#fig-missing-pattern width="84%" fig-align="center"}""":
    """![Eksik veri dağılım haritası: Araştırma sırasında ailelerden alınamayan veya boş bırakılan cevapların hangi konularda yoğunlaştığını gösterir. Okuma anahtarı: Gözlem (veri) eksikliğinin çok düşük olduğu (%0,3 civarı) görülmektedir. Sağlıklı çocuklarda doğal olarak sorulmayan hastalık soruları bu haritaya dâhil edilmemiştir.](docs/assets/figures/carbon/primary/fig-06-missing-pattern-primary.png){#fig-missing-pattern width="84%" fig-align="center"}"""
}

for old, new in replacements.items():
    content = content.replace(old, new)

with open(file_path, "w", encoding="utf-8") as f:
    f.write(content)

print("Part 1 replacements done.")
