import sys

file_path = "chapters/04_bulgular.qmd"

with open(file_path, "r", encoding="utf-8") as f:
    content = f.read()

replacements = {
    """#| tbl-cap: "Yalnız DM grubunda yürütülen klinik alt-analizler, satırlar analiz türüne göre gruplanmıştır: metabolik kontrol (HbA1c) × ebeveynlik etkileşimi, hastalık süresinin biçimi (kübik spline ile doğrusal karşılaştırması) ve tanı yaşı katmanları için ebeveynlik ilişkileri (metabolik kontrol alt-örneklemi n = 39). Sütunlar her analizin etki büyüklüğünü, güven aralığını, anlamlılık ölçütünü ve ilgili güç/açıklanan varyans göstergesini verir. Okuma anahtarı: bu alt-örneklem küçüktür ve küçük-orta etkiler için sınırlı güçtedir; sıfırdan ayırt edilemeyen etkiler ilişki yok değil, bu güçte gösterilemez olarak okunur." """:
    """#| tbl-cap: "Diyabet klinik bulguları alt-analizi: Sadece diyabetli gruptaki çocukların (HbA1c kan şekeri, hastalık süresi ve tanı konma yaşı) klinik durumları ile annelerinin ebeveynlik tutumları arasındaki ilişkiyi inceler. Okuma anahtarı: Bu tabloda yer alan veri grubu daha küçük olduğu için (örneğin kan şekeri olan 39 çocuk), istatistiksel farklılık görülmemesi 'kesinlikle ilişki yok' demekten çok 'bu küçük grupta bir ilişki ispatlanamadı' anlamına gelir." """,

    """![[KEŞİFSEL · İKİNCİL] Trifaktör doğrulayıcı faktör analizi (CFA) yükleme mimarisi: her ebeveynlik maddesinin varyansı ortak özellik (trait), indeks-yöntem ve kardeş-yöntem bileşenlerine ayrılır ve madde bazında standardize yüklemeler çizilir (bu grafik model uyum indekslerini değil, yükleme mimarisini gösterir). Model, anne, indeks çocuk ve kardeşin aynı tutumu raporladığı çok-bilgi-veren yapıyı temel alır. Okuma anahtarı: bir madde ortak özellik bileşenine yüklendiğinde fark rapor edenden bağımsız ortak bir özelliği, yöntem (bilgi-veren) bileşenine yüklendiğinde farkın kim rapor ediyor'a bağlı kısmını yansıtır.](docs/assets/figures/carbon/phase2/phase2_f01_trifactor.svg){#fig-p2-trifactor width="80%" fig-align="center"}""":
    """![Trifaktör (üçlü) analiz modeli: Anne, sağlıklı kardeş ve diyabetli çocuğun ebeveynliğe dair verdiği yanıtları inceleyerek, bu cevapların 'gerçek ortak bir tutumu' mu (merkez), yoksa 'kişinin kendi bakış açısını' mı (kenarlar) yansıttığını ayrıştırır. Okuma anahtarı: Ortadaki büyük daireye bağlanan çizgiler ailenin ortak gerçeğini, sağdaki ve soldaki dairelere bağlananlar ise o kişiye özel (taraflı) algıyı gösterir.](docs/assets/figures/carbon/phase2/phase2_f01_trifactor.svg){#fig-p2-trifactor width="80%" fig-align="center"}""",

    """![[KEŞİFSEL · İKİNCİL] Taban-duyarlı madde-yanıt kuramı (dereceli yanıt modeli, GRM) ile kestirilen latent yetenek (θ) grup farkları: reddetme gibi tabana yığılan maddelerin ham toplam puanla kötü ölçülen kısmı, her bireye tabana duyarlı bir latent θ atanarak yeniden değerlendirilir ve grup farkı bu latent ölçekte gösterilir. Grafik θ dağılımlarını ve iki-grup latent farkını (kovaryat-ayarsız d) sunar. Okuma anahtarı: bu ayarsız latent-d, birincil hattaki kovaryat-ayarlı çok düzeyli GRM katsayısından (β) farklı bir hedef parametredir ve onunla karıştırılmamalıdır; θ ile ham puan karşılaştırmasının yorumu Tartışma'ya bırakılmıştır.](docs/assets/figures/carbon/phase2/phase2_f03_floor_irt.svg){#fig-p2-floor-irt width="80%" fig-align="center"}""":
    """![Yanıt yığılmasını düzelten gelişmiş analiz grafiği (Madde-yanıt kuramı): Ailelerin ankette genellikle en düşük ('hiçbir zaman') seçeneğine yığılması problemini çözen çok daha hassas bir istatistiksel modele dayanır. Okuma anahtarı: Bu grafik, basit toplam puanlar yerine her bireyin anket sorularındaki gizli eğilimini (θ) bularak diyabetli ve kontrol grupları arasındaki asıl 'kapatılamayan farkı' gösterir.](docs/assets/figures/carbon/phase2/phase2_f03_floor_irt.svg){#fig-p2-floor-irt width="80%" fig-align="center"}""",

    """![[KEŞİFSEL · İKİNCİL] H1 çocuk algısı çoklu-evren (multiverse) spesifikasyon eğrisi: dört EMBU-C alt ölçeğinin her biri için makul tüm analitik seçim birleşimlerinde (kovaryat, yöntem, alt örneklem) kestirilen grup etkisi bir dağılım olarak çizilir. Dört alt ölçek ayrı estimand olduğundan her biri ayrı panelde, panel-içi spesifikasyon sırası ve panel-içi medyan β ile gösterilir; birincil estimand (reddetme) ilk paneldedir ve estimand'lar tek eğride birleştirilmez, tek bir global test üretilmez. Okuma anahtarı: bir paneldeki etki spesifikasyonlar boyunca işaretini/yönünü ne kadar koruyorsa bulgu seçimlere karşı o kadar sağlamdır; bu bir dağılımdır, tek bir p değeri değildir.](docs/assets/figures/carbon/phase2/phase2_f05_h1_spec_curve.svg){#fig-p2-h1-spec width="88%" fig-align="center"}""":
    """![Analiz sağlama (çoklu-evren / multiverse) grafiği: Araştırmadaki istatistiksel yöntem, kontrol edilen özellikler ve veri setinde yapılabilecek olası tüm makul değişiklik senaryolarında sonuçların değişip değişmeyeceğini (sağlamlığını) test eder. Okuma anahtarı: Noktaların birikim yönü değişmiyor ve çizginin üstünde veya altında kalmaya devam ediyorsa, farklı hesaplama yöntemleri seçilse bile asıl sonucun/bulgunun değişmeyeceği anlamına gelir.](docs/assets/figures/carbon/phase2/phase2_f05_h1_spec_curve.svg){#fig-p2-h1-spec width="88%" fig-align="center"}""",

    """![[KEŞİFSEL · İKİNCİL] Bu çalışmanın alt ölçek etkilerini dış literatürle karşılaştıran referans etki-büyüklüğü grafiği (biçimsel meta-analiz değildir): çalışmalar yapı (alan) bazında ayrı panellerde gösterilir — bu çalışmanın dört EMBU-C alt ölçeği ile kronik hastalık/ebeveynlik (Pinquart 2013), ebeveyn stresi (Pinquart 2018), maternal depresyon (Lovejoy 2000) ve kardeş içselleştirme (Vermaes 2012) alanlarındaki dört dış çalışma. Karşılaştırılabilirlik için tüm etkiler standartlaştırılmış etki büyüklüğü birimine getirilmiş (bu çalışmanın noktaları iki-grup Hedges g olarak yeniden hesaplanmış, dış çalışmalar kendi standart etkileriyle), her noktanın özgün metriği (Hedges g / Cohen d / korelasyondan dönüştürülmüş r→d) nokta yanında etiketli ve phase2_meta_combined_studies.csv dosyasının orig_metric sütununda kayıtlıdır. Okuma anahtarı: farklı yapılar ve özgün metrikler ölçüldüğünden ortak-estimand'lı havuzlama yapılmamış, havuzlanmış elmas ve dikey havuz çizgisi bilinçle gösterilmemiştir; panel yalnız yön ve büyüklük bandı kıyası için okunur, biçimsel meta-analiz olarak değil.](docs/assets/figures/carbon/phase2/phase2_f06_meta_forest.svg){#fig-p2-meta-forest width="82%" fig-align="center"}""":
    """![Tez sonuçlarının dış dünya (literatür) ile kıyaslanması: Bu araştırmada elde edilen etkilerin (diyabetin ebeveynliğe etkisi), dünyada yapılmış diğer büyük araştırmalardaki (kronik hastalık, anne stresi vb.) etkilerle boyutsal olarak nasıl bir paralellik gösterdiğinin haritasıdır. Okuma anahtarı: Diğer araştırmaların sonuçları yan yana konularak, bu tezde bulunan etkinin diğer hastalık ya da psikolojik stres faktörleriyle benzer veya farklı boyutta olup olmadığı görsel olarak karşılaştırılmıştır.](docs/assets/figures/carbon/phase2/phase2_f06_meta_forest.svg){#fig-p2-meta-forest width="82%" fig-align="center"}""",

    """![[KEŞİFSEL · İKİNCİL] Genişletilmiş klinik karar modeli net fayda ısı haritası: hücreler eşik olasılığı × maliyet oranı (c) ızgarasında net faydayı [NB = TP/n − (FP/n)·c·(p_t/(1−p_t))] gösterir. c = 1 satırı Vickers-Elkin standart karar eğrisi analizine (DCA) birebir indirgenir; c > 1 satırları yanlış-pozitif zararının daha ağır tartıldığı keşifsel duyarlılık senaryolarıdır. Okuma anahtarı: metinde raporlanan standart net fayda c = 1 satırından, standardize net fayda (sNB) ise bu değerin prevalansa (0,27) bölünmesiyle elde edilir; standart yorum için yalnız c = 1 satırı esas alınır.](docs/assets/figures/carbon/phase2/phase2_f12_dca_heatmap.png){#fig-p2-dca-heatmap width="84%" fig-align="center"}""":
    """![Genişletilmiş klinik net fayda ısı haritası: Annenin ebeveynlik tutumlarına bakarak depresyon riski olup olmadığına karar vermenin 'sağlayacağı fayda' ile 'yanlış alarm vermenin zararı' arasındaki dengeyi özetler. Okuma anahtarı: Renklerin koyuluğu modelin kullanılmasının doktorlara ve hastalara sağlayacağı net faydayı (kazancı) ifade eder. 'c=1' satırı temel ölçüttür; yanlış alarmın maliyeti arttıkça (c yükseldikçe) faydanın nasıl değiştiği incelenir.](docs/assets/figures/carbon/phase2/phase2_f12_dca_heatmap.png){#fig-p2-dca-heatmap width="84%" fig-align="center"}""",

    """![[KEŞİFSEL · İKİNCİL] Diferansiyel ebeveynlik testi (PDT) yön ve etki büyüklüğü profili: annenin aynı ailedeki iki çocuğa (indeks çocuk ile sağlıklı kardeş) yönelik tutum farkı, dört EMBU boyutunda aile içi işaretli etki büyüklüğü (d) olarak çizilir; anlamlılık Holm düzeltmesiyle değerlendirilir. Okuma anahtarı: her alt ölçekte işaretli d, farkın sıfırın hangi yanında ve ne büyüklükte olduğunu gösterir; ayrı çözümlenen baba-kayırması kontrastı bu dört alt ölçek profiline dahil değildir.](docs/assets/figures/carbon/exploratory/expl_f02_pdt_direction.svg){#fig-expl-pdt width="82%" fig-align="center"}""":
    """![Farklılaşmış (diferansiyel) ebeveynlik testi grafiği: Annenin aynı evin içinde diyabetli çocuğuna farklı, sağlıklı çocuğuna farklı davranıp davranmadığına (taraf tutup tutmadığına) bakar. Okuma anahtarı: Çubukların sıfır çizgisinden sağa veya sola doğru sapması, annenin hangi çocuğa doğru eğilim gösterdiğini (farkın büyüklüğünü) ifade eder. Merkezde (sıfırda) kalan çubuklar ayrımcılık olmadığını gösterir.](docs/assets/figures/carbon/exploratory/expl_f02_pdt_direction.svg){#fig-expl-pdt width="82%" fig-align="center"}""",

    """![[KEŞİFSEL · İKİNCİL] Anne komorbiditesi ve depresif belirti ilişkisi: annenin başka bir sağlık komorbiditesi taşıyıp taşımamasına göre depresif belirti (Beck) düzeyi ve gruplar arası antidepresan kullanımı kompozisyonu bağlamsal olarak betimlenir. Okuma anahtarı: komorbidite ile Beck puanı arasındaki işaretli etki büyüklüğü ilişkinin yön ve büyüklüğünü gösterir; antidepresan kullanım farkı bir etki büyüklüğü değil, grup kompozisyon gerçeğidir.](docs/assets/figures/carbon/exploratory/expl_f03_comorbidity.svg){#fig-expl-comorbidity width="80%" fig-align="center"}""":
    """![Anne ek hastalığı (komorbidite) ve depresyon ilişkisi grafiği: Annenin diyabet dışında bilinen başka bir kronik hastalığı olup olmamasının, annenin depresyon puanı ve antidepresan kullanımıyla ilişkisini özetler. Okuma anahtarı: Ek hastalığı olan anneler ile olmayan annelerin ruhsal sağlık (Beck) puanı arasındaki fark, çubukların büyüklüğü ve yönü ile görselleştirilmiştir.](docs/assets/figures/carbon/exploratory/expl_f03_comorbidity.svg){#fig-expl-comorbidity width="80%" fig-align="center"}""",

    """#| tbl-cap: "H1 dönem duyarlılığı çözümlemesi: birincil H1 estimandı (eşit-rol, kovaryat-ayarlı, aile rastgele kesişimli çok düzeyli grup ana etkisi), iki grubun en dengeli ortak-takvim dilimi olan 2023 alt örnekleminde (n = 40 kontrol, 108 DM indeks aile) dört EMBU-C alt ölçeği için yeniden kestirilmiştir; çoklu karşılaştırma BH-FDR ile düzeltilmiştir. Sütunlar her alt ölçek için 2023 katsayısını (b), %95 güven aralığını, FDR-düzeltilmiş q değerini ve karşılaştırma için tam örneklem katsayısını verir. Okuma anahtarı: tam örneklemde kestirilen etkiler dönem-dengeli alt örneklemde de sıfırdan ayırt ediliyorsa dönem/kohort karışması olasılığı azalır; küçülen alt örneklemde güç kaybı da ayrı bir açıklamadır." """:
    """#| tbl-cap: "H1 dönemsel (zaman) sağlama tablosu: Araştırmaya katılan hastaların geldikleri tarihler (örneğin pandemi dönemi vb.) sonuçları etkilemiş olabilir mi sorusuna yanıt arar. Sadece tarihsel olarak en dengeli yığılmanın olduğu '2023 yılı' hastaları izole edilerek çocuk algısı analizi (H1) tekrarlanmıştır. Okuma anahtarı: Tüm veride bulunan farklılık, sadece 2023 yılı verisinde de geçerli çıkıyorsa (güven aralığı sıfırı içermiyorsa), ulaşılan sonucun dönemsel bir yanılgı olmadığı doğrulanmış olur." """,

    """#| tbl-cap: "Robustluk özeti: çoklu evren ve TOST. Birincil bulguların analiz seçimlerine karşı kararlılığı iki katmanda toplanır; çoklu evren (spesifikasyon eğrisi) satırları EMBU alt ölçekleri, kovaryat setleri, tahmin yöntemleri ve alt örneklemlerin makul birleşimleri boyunca anlamlı spesifikasyon oranını, TOST (iki tek-yönlü test) satırları ise önceden belirlenen SMD eşdeğerlik sınırındaki eşdeğerlik kararını verir. Okuma anahtarı: çoklu evren oranı bir dağılım özetidir (tek test değildir; renkle işaretli nominal anlamlılık çokluk için düzeltilmemiştir); TOST 'Eşdeğer' kararı seçilen eşdeğerlik sınırına koşulludur, mutlak değildir." """:
    """#| tbl-cap: "Genel sağlamlık (robustluk) özeti: Araştırmadaki ana bulguların, farklı matematiksel hesaplamalarda, farklı kontrol değişkenlerinde veya eşdeğerlik testlerinde ne kadar sarsılmaz (sağlam) kaldığını özetleyen nihai doğrulama tablosudur. Okuma anahtarı: Tablonun gösterdiği sonuçlar, elde edilen klinik bulguların küçük analiz oynamalarından veya yöntem değişikliklerinden etkilenmeyecek kadar kararlı olduğunu teyit etmek için okunur." """,

    """#| tbl-cap: "Duyarlılık özeti: ölçülmemiş karıştırıcı ve falsifikasyon (satırlar analiz türüne göre gruplanmıştır). Gözlemsel tasarımın iki tehdidi bir arada raporlanır: ölçülmemiş (modele girmemiş) bir karıştırıcının bulguyu değiştirme gücü (sağlamlık değeri RV_q ve E-değeri) ve ilişkinin beklenmediği yerde sahte sinyal üretilip üretilmediğini yoklayan negatif kontrol/falsifikasyon eşlemeleri; ayrıca eksik-veri yöntemi ve sosyoekonomik durum tanımı seçimlerine karşı katsayı kararlılığı. Okuma anahtarı: RV_q ve E-değeri ne kadar büyükse gizli bir karıştırıcının bulguyu değiştirmesi için o kadar güç gerekir; negatif kontrol satırlarında beklenmedik bir anlamlılık, tam rastgele bir kontrol değil olası bir dönem/kohort vekili uyarısı olarak okunur." """:
    """#| tbl-cap: "Gizli faktör ve sahte sinyal (duyarlılık) özeti: Bu tablo araştırmada 'gözden kaçan gizli bir etken' (örneğin ölçülmemiş bir psikolojik özellik) varsa bunun mevcut sonuçları devirip deviremeyeceğini hesaplar. Ayrıca ilişkinin asla olmaması gereken yerlerde 'sahte bir sonuç' çıkıp çıkmadığı da denetlenir. Okuma anahtarı: 'RV_q' ve 'E-değeri' olarak adlandırılan sayılar ne kadar büyükse, bizim göremediğimiz gizli bir faktörün tezin sonuçlarını çürütme ihtimali o kadar zordur." """,

    """![Çoklu evren spesifikasyon eğrisi — birincil sağlamlık katmanı. Her panelde, EMBU alt ölçeği, kovaryat seti, tahmin yöntemi ve alt örneklem seçimlerinin makul birleşimlerinden oluşan spesifikasyonlar Cohen d etki büyüklüğüne göre sıralanmıştır; nokta rengi her bir spesifikasyonun nominal anlamlılığını gösterir. Okuma anahtarı: bu bir dağılımdır, tek test değildir; noktaların hangi yönde toplandığına ve büyüklüğe göre sıralı örüntüye bakılır. Renkle işaretli nominal anlamlılık çokluk için düzeltilmemiş olduğundan, global yargı ayrı bir permütasyon testine dayandırılır.](docs/assets/figures/carbon/primary/fig-22-specification-curve.svg){#fig-specification-curve width="90%" fig-align="center"}""":
    """![Çoklu-evren analiz sağlamlık haritası: Ana ebeveynlik boyutlarında yapılan tüm olası analiz senaryolarının (farklı yaş grupları, farklı gelir hesaplamaları vb.) uç uca eklendiğinde aynı etkiyi yaratıp yaratmadığıdır. Okuma anahtarı: Renkli noktaların oluşturduğu çizginin şekli ve yönü, hesaplama yöntemi değiştirilse de tezin ulaştığı asıl sonucun (fark var veya fark yok) ne kadar kararlı bir şekilde sabit kaldığını gösterir.](docs/assets/figures/carbon/primary/fig-22-specification-curve.svg){#fig-specification-curve width="90%" fig-align="center"}""",

    """![Ölçülmemiş karıştırıcı duyarlılık konturu (sensemakr). Noktalar EMBU-P alt ölçekleri için grup (T1DM maruziyeti) kısmi R² ve RV_q kesişimini, arka plan konturları ise bir ortak karıştırıcının varsayımsal gücünü göstermektedir; eksenler, gizli bir karıştırıcının maruziyet ve sonuçla ne kadar ilişkili olması gerektiğini niceler. sensemakr çerçevesinin 'treatment' ekseni bu gözlemsel tasarımda bir müdahaleyi değil grup/maruziyet göstergesini temsil eder ve nedensellik iddiası taşımaz. Okuma anahtarı: bir bulguyu sıfırlamak için gereken kısmi R² eşiği ne kadar yüksekse sonuç gizli karıştırıcıya karşı o kadar dayanıklıdır; düşük bir eşik ise temkinli okuma gerektirdiği anlamına gelir.](docs/assets/figures/carbon/primary/fig-23-sensemakr-contour.png){#fig-sensemakr-contour width="80%" fig-align="center"}""":
    """![Gözden kaçan 'gizli etken' dayanıklılık (sensemakr) haritası: Araştırmada hiç hesaba katılmamış yepyeni bir özellik olsa (örneğin bambaşka bir genetik hastalık vb.), bunun tezin sonuçlarını geçersiz kılıp kılamayacağını matematiksel olarak test eder. Okuma anahtarı: Haritadaki nokta (bizim ulaştığımız sonuç) kırmızı uyarı eşiklerinden ne kadar uzaktaysa, dışarıdan gelecek sürpriz ve gizli bir etkinin tezin ana fikrini sarsması o kadar zor (sonuç o kadar sağlam) demektir.](docs/assets/figures/carbon/primary/fig-23-sensemakr-contour.png){#fig-sensemakr-contour width="80%" fig-align="center"}""",

    """#| tbl-cap: "Bayesçi çift raporlama (satırlar hipoteze göre gruplanmıştır). H1 ve H3 alt ölçekleri için brms çok düzeyli modellerinden elde edilen posterior fark katsayısı, güvenilir aralık, yön olasılığı (pd) ve Bayes faktörü (BF₁₀), her modelin MCMC yakınsama tanılarıyla birlikte tek yerde toplanır. Tüm modellerde MCMC yakınsaması sağlıklıdır: Rhat ≤ 1,003; en düşük ESS oranı ≥ 0,09; ıraksayan geçiş yoktur. Okuma anahtarı: BF₁₀ Jeffreys ölçeğinde bir kanıt gücü ölçütüdür ve birden küçükse fark-yokluğu (H0) lehine kanıt anlamına gelir; ESS bir örneklem büyüklüğü değil, kestirimin Monte Carlo kararlılığını gösteren bir tanı ölçütüdür." """:
    """#| tbl-cap: "Bayesçi (Gelişmiş İstatistik) doğrulama özeti: Çocuk algısı (H1) ve anne bildirimi (H3) hipotezleri için ulaşılan sonuçların, 'Bayesçi analiz' adı verilen alternatif ve güçlü bir hesaplamayla da uyuştuğunu topluca belgeleyen tablodur. Okuma anahtarı: Tablodaki BF₁₀ (Bayes Faktörü) değeri; sonucun, tesadüfi bir bulgudan ziyade ne kadar güçlü bir kanıt içerdiğini oransal olarak ifade eder." """,

    """#| tbl-cap: "Genel bulgu sentezi — bütünleşik özet (kapstone) tablosu. Birincil (H1–H5) ve genişletilmiş nicel bulgular ile karma tezin niteliksel kolunun deneyimsel bağlamı, hipotez satırları boyunca tek bir özette toplanır; sütunlar her hipotez için nicel kararı, (varsa) niteliksel bağlamı, yakınsama tipini ve nedensellik/kapsam çekincesini verir. Okuma anahtarı: satırlar yatay okunur ve dört sütun birlikte değerlendirilir; yakınsama (nicel ile niteliksel kolun aynı yönü göstermesi) bir bağlam zenginleştirmesidir, nedensellik göstergesi değildir." """:
    """#| tbl-cap: "Genel sentez (bütünleşik özet) tablosu: Araştırmadaki 5 ana hipotezin (H1-H5) sayılara dayanan nicel sonuçları ile görüşmelere dayanan nitel sonuçlarının (deneyimsel boyutun) bir araya getirildiği büyük kapanış özetidir. Okuma anahtarı: Her hipotez satırında nicel verinin ne dediği, annelerin kendi ifadelerinin (nitel) ne dediği ve bu iki farklı bilimsel dünyanın birbiriyle uyum gösterip göstermediği (yakınsama) yan yana izlenir." """
}

for old, new in replacements.items():
    content = content.replace(old, new)

with open(file_path, "w", encoding="utf-8") as f:
    f.write(content)

print("Part 4 replacements done.")
