import sys

file_path = "chapters/04_bulgular.qmd"

with open(file_path, "r", encoding="utf-8") as f:
    content = f.read()

replacements = {
    """#| tbl-cap: "Aracılık analiz sonuçları: 'Anne depresyonu → annenin reddetme tutumu → çocuğun reddedildiğini hissetmesi' şeklinde bir zincirleme etki olup olmadığını test eder. Okuma anahtarı: 'Dolaylı etki' sütunundaki güven aralığı sıfırı içeriyorsa, bu zincirleme bağlantının çalışmadığına, yani ilişkinin annenin bildiriminden 'aracı olarak' geçmediğine hükmedilir." """:
    """#| tbl-cap: "Aracılık analiz sonuçları: 'Anne depresyonu → annenin reddetme tutumu → çocuğun reddedildiğini hissetmesi' şeklinde bir zincirleme etki olup olmadığını test eder. Okuma anahtarı: 'Dolaylı etki' sütunundaki güven aralığı sıfırı içeriyorsa, bu zincirleme bağlantının çalışmadığına, yani ilişkinin annenin bildiriminden 'aracı olarak' geçmediğine hükmedilir. Sonuç: Bu analiz, depresyon ile çocuğun algısı arasındaki bağın 'annenin kendi tutumu' üzerinden aktarılmadığını (aracılığın işlemediğini) göstermiştir." """,

    """#| tbl-cap: "Aileleri gruplara (profillere) ayırma analizi (LPA/LCA): Tüm ailelerin psikolojik ve sosyoekonomik verilerine bakılarak veri setinin içinde kendiliğinden doğal gruplar/profiller olup olmadığını arar. Tablo, bu profillerin 1'den 5'e kadar sınıflandırılmasının ne kadar mantıklı/uyumlu (BIC/Entropi) olduğunu gösterir. Okuma anahtarı: Entropinin 0,80'e yakın ve BIC'in düşük olması, ayrılan grupların birbirine karışmayan temiz profiller olduğunu gösterir." """:
    """#| tbl-cap: "Aileleri gruplara (profillere) ayırma analizi (LPA/LCA): Tüm ailelerin psikolojik ve sosyoekonomik verilerine bakılarak veri setinin içinde kendiliğinden doğal gruplar/profiller olup olmadığını arar. Tablo, bu profillerin 1'den 5'e kadar sınıflandırılmasının ne kadar mantıklı/uyumlu (BIC/Entropi) olduğunu gösterir. Okuma anahtarı: Entropinin 0,80'e yakın ve BIC'in düşük olması, ayrılan grupların birbirine karışmayan temiz profiller olduğunu gösterir. Sonuç: Aileler gizli özelliklerine göre üç temel profile ayrılmış; ancak diyabet tanısının bu profillerden (kötü veya iyi gruptan) herhangi birine düşme ihtimalini değiştirmediği görülmüştür." """,

    """![Aile profilleri ayırma analiz grafikleri: İstatistiksel programın veride kaç farklı 'tip/profil' aile bulduğunu ve bu ayrımların (3, 4 veya 5 grup) ne kadar isabetli olduğunu gösterir. Okuma anahtarı: Düşük BIC çizgisi ve yüksek Entropi uyumu arzu edilir. Veriler, araştırılan grupta en isabetli seçeneğin aileleri 3 farklı temel profile ayırmak olduğunu göstermiştir.](docs/assets/figures/carbon/primary/fig-15-lpa-fit-indices.svg){#fig-lpa-fit-indices width="78%" fig-align="center"}""":
    """![Aile profilleri ayırma analiz grafikleri: İstatistiksel programın veride kaç farklı 'tip/profil' aile bulduğunu ve bu ayrımların (3, 4 veya 5 grup) ne kadar isabetli olduğunu gösterir. Okuma anahtarı: Düşük BIC çizgisi ve yüksek Entropi uyumu arzu edilir. Veriler, araştırılan grupta en isabetli seçeneğin aileleri 3 farklı temel profile ayırmak olduğunu göstermiştir. Sonuç olarak, diyabetli olmanın aileyi belirli bir kötü profile itmediği teyit edilmiştir.](docs/assets/figures/carbon/primary/fig-15-lpa-fit-indices.svg){#fig-lpa-fit-indices width="78%" fig-align="center"}""",

    """#| tbl-cap: "Aile içi ilişkilerin istatistiksel ağ (network) analizi sonuçları: Annelerin tutumları, kardeşlerin ilişkileri ve depresyon gibi 9 temel konunun birbiriyle nasıl bir 'örümcek ağı' gibi bağlandığını özetler. Okuma anahtarı: Hangi özelliğin ağın tam 'merkezinde' yer aldığını (en çok etkileşen/bağlanan konu) gösterir. Karşılaştırma testi (NCT), bu ilişki ağının diyabetli aileler ile sağlıklı ailelerde genel olarak benzer olduğunu göstermektedir." """:
    """#| tbl-cap: "Aile içi ilişkilerin istatistiksel ağ (network) analizi sonuçları: Annelerin tutumları, kardeşlerin ilişkileri ve depresyon gibi 9 temel konunun birbiriyle nasıl bir 'örümcek ağı' gibi bağlandığını özetler. Okuma anahtarı: Hangi özelliğin ağın tam 'merkezinde' yer aldığını (en çok etkileşen/bağlanan konu) gösterir. Sonuç: Karşılaştırma testi (NCT), bu ilişki ağının diyabetli aileler ile sağlıklı ailelerde (örneğin depresyonun aile içindeki bağları sarsma biçimi açısından) birbirine çok benzediğini göstermiştir." """,

    """![Aile içi ilişkilerin ağ (network) haritası: Ebeveynlik, kardeş ilişkisi ve depresyonun birbirine nasıl bağlandığını gösteren görseldir. Okuma anahtarı: Çizgilerin (kenarların) kalınlığı o iki konu arasındaki bağın ne kadar güçlü ve doğrudan olduğunu gösterir. Dairelerin (düğümlerin) büyüklüğü ise o konunun ailenin dinamiğinde ne kadar kilit (merkezî) bir rolde oturduğunu ifade eder.](docs/assets/figures/carbon/primary/fig-16-network-graph.svg){#fig-network-graph width="82%" fig-align="center"}""":
    """![Aile içi ilişkilerin ağ (network) haritası: Ebeveynlik, kardeş ilişkisi ve depresyonun birbirine nasıl bağlandığını gösteren görseldir. Okuma anahtarı: Çizgilerin (kenarların) kalınlığı o iki konu arasındaki bağın ne kadar güçlü ve doğrudan olduğunu gösterir. Dairelerin (düğümlerin) büyüklüğü ise o konunun ailenin dinamiğinde ne kadar kilit (merkezî) bir rolde oturduğunu ifade eder. Ağın genel şekline bakıldığında, diyabetin aile içi iletişim yumağını temelden bozmadığı görülmektedir.](docs/assets/figures/carbon/primary/fig-16-network-graph.svg){#fig-network-graph width="82%" fig-align="center"}""",

    """![Diyabetli ve kontrol ağlarının karşılaştırma testi (NCT): Diyabetli ailelerin ilişkilerindeki bağ yapısı ile kontrol ailelerinin bağ yapısı arasında genel bir fark olup olmadığını kontrol eden görseldir. Okuma anahtarı: 'p değeri' belirlenen kuralın altındaysa fark var demektir. Tablodaki veriler, genel yapının (örümcek ağının biçiminin) iki grup arasında benzer olduğunu göstermiştir.](docs/assets/figures/carbon/primary/fig-17-network-nct.svg){#fig-network-nct width="72%" fig-align="center"}""":
    """![Diyabetli ve kontrol ağlarının karşılaştırma testi (NCT): Diyabetli ailelerin ilişkilerindeki bağ yapısı ile kontrol ailelerinin bağ yapısı arasında genel bir fark olup olmadığını kontrol eden görseldir. Okuma anahtarı: 'p değeri' belirlenen kuralın altındaysa fark var demektir. Tablodaki veriler, genel yapının (örümcek ağının biçiminin) iki grup arasında benzer olduğunu, yani diyabetin bağların yapısını değiştirmediğini kanıtlamıştır.](docs/assets/figures/carbon/primary/fig-17-network-nct.svg){#fig-network-nct width="72%" fig-align="center"}""",

    """#| tbl-cap: "Anne depresyonu tarama modeli performansı: Annelerin depresyon riskini temel bilgilerle (yaş, çocuk sayısı, vb.) ve ebeveynlik tutumlarıyla (geniş model) ne kadar doğru sınıflandırabildiğimizi gösterir. Okuma anahtarı: AUC (eğri altı alan) modelin ayırma gücünü gösterir; 0,5 rastgele atış yapmakla eşdeğerken, 0,70-0,80 arası kabul edilebilir, iyi bir başarıyı temsil eder." """:
    """#| tbl-cap: "Anne depresyonu tarama modeli performansı: Annelerin depresyon riskini temel bilgilerle (yaş, çocuk sayısı, vb.) ve ebeveynlik tutumlarıyla (geniş model) ne kadar doğru sınıflandırabildiğimizi gösterir. Okuma anahtarı: AUC (eğri altı alan) modelin ayırma gücünü gösterir; 0,5 rastgele atış yapmakla eşdeğerken, 0,70-0,80 arası kabul edilebilir, iyi bir başarıyı temsil eder. Sonuç: Annelerin ebeveynlik tutumlarına bakarak kimin depresyonda olduğunu tahmin etmek çok zordur; bu modelin klinik olarak net bir teşhis katkısı bulunamamıştır." """,

    """![Klinik karar (fayda/zarar) eğrisi: Bu modeli kullanarak anneleri depresyon açısından taramanın, 'herkesi tara' veya 'hiç kimseyi tarama' gibi körleme stratejilere göre ne kadar net fayda (pratik kazanç) sağlayacağını gösterir. Okuma anahtarı: Model eğrisinin diğer iki basit (körleme) çizginin üzerinde kaldığı her nokta, modelin kullanılmasının doktorlara ve hastalara zaman/emek açısından fayda sağladığı (gereksiz işlem yaptırmadığı) anlamına gelir.](docs/assets/figures/carbon/primary/fig-19-clinical-dca.svg){#fig-clinical-dca width="86%" fig-align="center"}""":
    """![Klinik karar (fayda/zarar) eğrisi: Bu modeli kullanarak anneleri depresyon açısından taramanın, 'herkesi tara' veya 'hiç kimseyi tarama' gibi körleme stratejilere göre ne kadar net fayda (pratik kazanç) sağlayacağını gösterir. Okuma anahtarı: Model eğrisinin diğer iki basit (körleme) çizginin üzerinde kaldığı her nokta, modelin kullanılmasının doktorlara ve hastalara zaman/emek açısından fayda sağladığı anlamına gelir. Grafikte, tutumlara bakarak depresyon aramamanın net faydasının çok düşük olduğu ve sadece düşük tarama eşiklerinde ufak bir kazanç sağladığı görülmektedir.](docs/assets/figures/carbon/primary/fig-19-clinical-dca.svg){#fig-clinical-dca width="86%" fig-align="center"}""",

    """#| tbl-cap: "Diyabet klinik bulguları alt-analizi: Sadece diyabetli gruptaki çocukların (HbA1c kan şekeri, hastalık süresi ve tanı konma yaşı) klinik durumları ile annelerinin ebeveynlik tutumları arasındaki ilişkiyi inceler. Okuma anahtarı: Bu tabloda yer alan veri grubu daha küçük olduğu için (örneğin kan şekeri olan 39 çocuk), istatistiksel farklılık görülmemesi 'kesinlikle ilişki yok' demekten çok 'bu küçük grupta bir ilişki ispatlanamadı' anlamına gelir." """:
    """#| tbl-cap: "Diyabet klinik bulguları alt-analizi: Sadece diyabetli gruptaki çocukların (HbA1c kan şekeri, hastalık süresi ve tanı konma yaşı) klinik durumları ile annelerinin ebeveynlik tutumları arasındaki ilişkiyi inceler. Okuma anahtarı: İstatistiksel farklılık görülmemesi 'kesinlikle ilişki yok' demekten çok 'bu küçük grupta bir ilişki ispatlanamadı' anlamına gelir. Sonuç: Çocukların kan şekeri seviyesi veya diyabete yakalandıkları yaş ile annelerinin tutumları arasında istatistiksel olarak gösterilebilen bir bağlantı bulunamamıştır." """
}

for old, new in replacements.items():
    if old in content:
        content = content.replace(old, new)
    else:
        print(f"Warning: Old text not found.\n{old[:100]}...")

with open(file_path, "w", encoding="utf-8") as f:
    f.write(content)

print("Caption enhancements for exploratory sections done.")
